/**
 * SIH 26006 Maritime Intelligence Platform
 * Module 19: Canonical Fleets, Owners, Commercial Operators & Vessel Deployment Registry
 */

import {
  FleetVesselRecord,
  FleetOwnerEntity,
  FleetOperatorEntity,
} from '../../types/fleets';

export const OWNERS_REGISTRY: FleetOwnerEntity[] = [
  {
    id: 'own-euronav',
    name: 'Euronav NV / CMB.TECH',
    country: 'Belgium',
    headquarters: 'Antwerp',
    vesselCount: 7,
    totalDwt: 1740000,
    vesselClasses: ['VLCC', 'Suezmax'],
    primaryOperators: ['Vitol / Mansel Oil', 'TotalEnergies CSSA', 'Shell International Trading & Shipping'],
  },
  {
    id: 'own-frontline',
    name: 'Frontline Ltd',
    country: 'Norway',
    headquarters: 'Oslo',
    vesselCount: 6,
    totalDwt: 1560000,
    vesselClasses: ['VLCC', 'Suezmax', 'Aframax'],
    primaryOperators: ['Trafigura Maritime Logistics', 'Vitol / Mansel Oil', 'Shell International Trading & Shipping'],
  },
  {
    id: 'own-starbulk',
    name: 'Star Bulk Carriers Corp',
    country: 'Greece',
    headquarters: 'Athens',
    vesselCount: 6,
    totalDwt: 820000,
    vesselClasses: ['Capesize', 'Panamax', 'Supramax'],
    primaryOperators: ['Cargill Ocean Transportation', 'Rio Tinto Shipping', 'BHP Marine Logistics'],
  },
  {
    id: 'own-oldendorff',
    name: 'Oldendorff Carriers GmbH',
    country: 'Germany',
    headquarters: 'Lübeck',
    vesselCount: 6,
    totalDwt: 780000,
    vesselClasses: ['Capesize', 'Panamax', 'Handysize'],
    primaryOperators: ['Oldendorff Commercial Desk', 'Cargill Ocean Transportation'],
  },
  {
    id: 'own-dht',
    name: 'DHT Holdings Inc',
    country: 'Bermuda',
    headquarters: 'Hamilton',
    vesselCount: 4,
    totalDwt: 1220000,
    vesselClasses: ['VLCC'],
    primaryOperators: ['Shell International Trading & Shipping', 'Trafigura Maritime Logistics'],
  },
  {
    id: 'own-goldenocean',
    name: 'Golden Ocean Group Ltd',
    country: 'Norway',
    headquarters: 'Oslo',
    vesselCount: 5,
    totalDwt: 740000,
    vesselClasses: ['Capesize', 'Panamax'],
    primaryOperators: ['Cargill Ocean Transportation', 'BHP Marine Logistics'],
  },
  {
    id: 'own-pacbasin',
    name: 'Pacific Basin Shipping Ltd',
    country: 'Hong Kong',
    headquarters: 'Hong Kong',
    vesselCount: 4,
    totalDwt: 195000,
    vesselClasses: ['Handysize', 'Supramax'],
    primaryOperators: ['Pacific Basin Pool Management'],
  },
  {
    id: 'own-nakilat',
    name: 'Nakilat Qatar Gas Transport',
    country: 'Qatar',
    headquarters: 'Doha',
    vesselCount: 4,
    totalDwt: 490000,
    vesselClasses: ['LNG Carrier'],
    primaryOperators: ['Shell International Trading & Shipping', 'TotalEnergies CSSA'],
  },
  {
    id: 'own-bwgroup',
    name: 'BW Group / BW LPG',
    country: 'Singapore',
    headquarters: 'Singapore',
    vesselCount: 4,
    totalDwt: 320000,
    vesselClasses: ['VLGC LPG Carrier', 'LNG Carrier'],
    primaryOperators: ['Trafigura Maritime Logistics', 'TotalEnergies CSSA'],
  },
  {
    id: 'own-scorpio',
    name: 'Scorpio Tankers Inc',
    country: 'Monaco',
    headquarters: 'Monaco',
    vesselCount: 4,
    totalDwt: 215000,
    vesselClasses: ['MR Product Tanker', 'Aframax'],
    primaryOperators: ['ST Shipping / Glencore', 'Trafigura Maritime Logistics'],
  },
  {
    id: 'own-maran',
    name: 'Maran Gas & Maritime',
    country: 'Greece',
    headquarters: 'Athens',
    vesselCount: 4,
    totalDwt: 680000,
    vesselClasses: ['LNG Carrier', 'VLCC'],
    primaryOperators: ['TotalEnergies CSSA', 'Shell International Trading & Shipping'],
  },
];

export const OPERATORS_REGISTRY: FleetOperatorEntity[] = [
  {
    id: 'op-cargill',
    name: 'Cargill Ocean Transportation',
    country: 'Switzerland',
    headquarters: 'Geneva',
    vesselCount: 9,
    totalDwt: 1140000,
    vesselClasses: ['Capesize', 'Panamax', 'Supramax'],
    primaryOwners: ['Star Bulk Carriers Corp', 'Golden Ocean Group Ltd', 'Oldendorff Carriers GmbH'],
  },
  {
    id: 'op-oldendorff',
    name: 'Oldendorff Commercial Desk',
    country: 'Germany',
    headquarters: 'Lübeck',
    vesselCount: 6,
    totalDwt: 780000,
    vesselClasses: ['Capesize', 'Panamax', 'Handysize'],
    primaryOwners: ['Oldendorff Carriers GmbH'],
  },
  {
    id: 'op-trafigura',
    name: 'Trafigura Maritime Logistics',
    country: 'Singapore',
    headquarters: 'Singapore',
    vesselCount: 8,
    totalDwt: 1650000,
    vesselClasses: ['VLCC', 'Suezmax', 'VLGC LPG Carrier', 'MR Product Tanker'],
    primaryOwners: ['Frontline Ltd', 'BW Group / BW LPG', 'Scorpio Tankers Inc'],
  },
  {
    id: 'op-glencore',
    name: 'ST Shipping / Glencore',
    country: 'Switzerland',
    headquarters: 'Baar',
    vesselCount: 5,
    totalDwt: 620000,
    vesselClasses: ['Aframax', 'MR Product Tanker', 'Supramax'],
    primaryOwners: ['Scorpio Tankers Inc', 'Frontline Ltd'],
  },
  {
    id: 'op-bhp',
    name: 'BHP Marine Logistics',
    country: 'Australia',
    headquarters: 'Melbourne',
    vesselCount: 5,
    totalDwt: 860000,
    vesselClasses: ['Capesize', 'Panamax'],
    primaryOwners: ['Star Bulk Carriers Corp', 'Golden Ocean Group Ltd'],
  },
  {
    id: 'op-rio',
    name: 'Rio Tinto Shipping',
    country: 'Singapore',
    headquarters: 'Singapore',
    vesselCount: 4,
    totalDwt: 720000,
    vesselClasses: ['Capesize'],
    primaryOwners: ['Star Bulk Carriers Corp'],
  },
  {
    id: 'op-shell',
    name: 'Shell International Trading & Shipping',
    country: 'United Kingdom',
    headquarters: 'London',
    vesselCount: 7,
    totalDwt: 1580000,
    vesselClasses: ['VLCC', 'LNG Carrier', 'Suezmax'],
    primaryOwners: ['Euronav NV / CMB.TECH', 'DHT Holdings Inc', 'Nakilat Qatar Gas Transport'],
  },
  {
    id: 'op-total',
    name: 'TotalEnergies CSSA',
    country: 'France',
    headquarters: 'Paris / Geneva',
    vesselCount: 6,
    totalDwt: 1240000,
    vesselClasses: ['LNG Carrier', 'VLCC', 'VLGC LPG Carrier'],
    primaryOwners: ['Maran Gas & Maritime', 'Nakilat Qatar Gas Transport', 'Euronav NV / CMB.TECH'],
  },
  {
    id: 'op-vitol',
    name: 'Vitol / Mansel Oil',
    country: 'Netherlands',
    headquarters: 'Rotterdam',
    vesselCount: 5,
    totalDwt: 1320000,
    vesselClasses: ['VLCC', 'Suezmax', 'Aframax'],
    primaryOwners: ['Euronav NV / CMB.TECH', 'Frontline Ltd'],
  },
  {
    id: 'op-pacbasin',
    name: 'Pacific Basin Pool Management',
    country: 'Hong Kong',
    headquarters: 'Hong Kong',
    vesselCount: 4,
    totalDwt: 195000,
    vesselClasses: ['Handysize', 'Supramax'],
    primaryOwners: ['Pacific Basin Shipping Ltd'],
  },
];

export const FLEET_VESSELS_REGISTRY: FleetVesselRecord[] = [
  // 1. VLCC Fleet
  {
    id: 101,
    name: 'OCEANIA STAR',
    imoNumber: 'IMO 9832101',
    vesselClass: 'VLCC',
    vesselType: 'Very Large Crude Carrier',
    dwt: 308000,
    grossTonnage: 162000,
    yearBuilt: 2021,
    flag: 'Marshall Islands',
    ownerId: 'own-euronav',
    ownerName: 'Euronav NV / CMB.TECH',
    ownerCountry: 'Belgium',
    operatorId: 'op-vitol',
    operatorName: 'Vitol / Mansel Oil',
    operatorCountry: 'Netherlands',
    fleetId: 'flt-euronav-crude',
    fleetName: 'Euronav Global Crude Fleet',
    cargoCategory: 'Crude Oil',
    primaryCommodity: 'Arabian Light Crude',
    deployment: {
      region: 'Middle East Gulf & Red Sea',
      country: 'Saudi Arabia',
      subArea: 'Ras Tanura Terminal Anchorage',
      latitude: 26.65,
      longitude: 50.16,
      status: 'loading',
      destinationPort: 'Ningbo-Zhoushan (CNNGB)',
      eta: '2026-09-28 10:00 UTC',
      speedKnots: 0.1,
      heading: 140,
    },
    ciiRating: 'B',
    dailyFuelConsumptionMt: 44.5,
  },
  {
    id: 102,
    name: 'DHT PEAK',
    imoNumber: 'IMO 9811402',
    vesselClass: 'VLCC',
    vesselType: 'Very Large Crude Carrier',
    dwt: 318000,
    grossTonnage: 165000,
    yearBuilt: 2019,
    flag: 'Hong Kong',
    ownerId: 'own-dht',
    ownerName: 'DHT Holdings Inc',
    ownerCountry: 'Bermuda',
    operatorId: 'op-shell',
    operatorName: 'Shell International Trading & Shipping',
    operatorCountry: 'United Kingdom',
    fleetId: 'flt-dht-vlcc',
    fleetName: 'DHT Deepwater Energy Fleet',
    cargoCategory: 'Crude Oil',
    primaryCommodity: 'Basrah Medium Crude',
    deployment: {
      region: 'Southeast Asia',
      country: 'Singapore',
      subArea: 'Malacca Strait Eastbound Lane',
      latitude: 2.15,
      longitude: 102.1,
      status: 'underway',
      destinationPort: 'Qingdao (CNQDG)',
      eta: '2026-09-20 18:00 UTC',
      speedKnots: 13.8,
      heading: 115,
    },
    ciiRating: 'A',
    dailyFuelConsumptionMt: 42.0,
  },
  {
    id: 103,
    name: 'FRONT ALTAIR',
    imoNumber: 'IMO 9745103',
    vesselClass: 'VLCC',
    vesselType: 'Very Large Crude Carrier',
    dwt: 299000,
    grossTonnage: 159000,
    yearBuilt: 2017,
    flag: 'Liberia',
    ownerId: 'own-frontline',
    ownerName: 'Frontline Ltd',
    ownerCountry: 'Norway',
    operatorId: 'op-trafigura',
    operatorName: 'Trafigura Maritime Logistics',
    operatorCountry: 'Singapore',
    fleetId: 'flt-frontline-tankers',
    fleetName: 'Frontline Global Tankers',
    cargoCategory: 'Crude Oil',
    primaryCommodity: 'Murban Crude Oil',
    deployment: {
      region: 'Asia-Pacific / Far East',
      country: 'China',
      subArea: 'East China Sea Approach to Ningbo',
      latitude: 29.85,
      longitude: 122.45,
      status: 'underway',
      destinationPort: 'Ningbo (CNNGB)',
      eta: '2026-09-14 06:00 UTC',
      speedKnots: 12.5,
      heading: 320,
    },
    ciiRating: 'B',
    dailyFuelConsumptionMt: 46.0,
  },
  {
    id: 104,
    name: 'MARAN CYGNUS',
    imoNumber: 'IMO 9855104',
    vesselClass: 'VLCC',
    vesselType: 'Very Large Crude Carrier',
    dwt: 320000,
    grossTonnage: 166000,
    yearBuilt: 2022,
    flag: 'Greece',
    ownerId: 'own-maran',
    ownerName: 'Maran Gas & Maritime',
    ownerCountry: 'Greece',
    operatorId: 'op-total',
    operatorName: 'TotalEnergies CSSA',
    operatorCountry: 'France',
    fleetId: 'flt-maran-tankers',
    fleetName: 'Maran Strategic Energy Fleet',
    cargoCategory: 'Crude Oil',
    primaryCommodity: 'Upper Zakum Heavy Crude',
    deployment: {
      region: 'West & Southern Africa',
      country: 'South Africa',
      subArea: 'Cape of Good Hope Detour Route',
      latitude: -34.8,
      longitude: 19.2,
      status: 'underway',
      destinationPort: 'Rotterdam (NLRTM)',
      eta: '2026-09-29 14:00 UTC',
      speedKnots: 13.2,
      heading: 295,
    },
    ciiRating: 'A',
    dailyFuelConsumptionMt: 41.5,
  },

  // 2. Capesize Dry Bulk Fleet
  {
    id: 105,
    name: 'STAR BOREALIS',
    imoNumber: 'IMO 9523105',
    vesselClass: 'Capesize',
    vesselType: 'Capesize Bulk Carrier',
    dwt: 182000,
    grossTonnage: 93500,
    yearBuilt: 2018,
    flag: 'Liberia',
    ownerId: 'own-starbulk',
    ownerName: 'Star Bulk Carriers Corp',
    ownerCountry: 'Greece',
    operatorId: 'op-rio',
    operatorName: 'Rio Tinto Shipping',
    operatorCountry: 'Singapore',
    fleetId: 'flt-starbulk-capes',
    fleetName: 'Star Bulk Mineral Fleet',
    cargoCategory: 'Dry Bulk',
    primaryCommodity: 'Pilbara High-Grade Iron Ore',
    deployment: {
      region: 'Australia & Oceania',
      country: 'Australia',
      subArea: 'Port Hedland Outer Anchorage',
      latitude: -20.25,
      longitude: 118.55,
      status: 'anchored',
      destinationPort: 'Qingdao (CNQDG)',
      eta: '2026-09-24 12:00 UTC',
      speedKnots: 0.2,
      heading: 210,
    },
    ciiRating: 'B',
    dailyFuelConsumptionMt: 32.5,
  },
  {
    id: 106,
    name: 'HENNING OLDENDORFF',
    imoNumber: 'IMO 9722106',
    vesselClass: 'Capesize',
    vesselType: 'Capesize Bulk Carrier',
    dwt: 208000,
    grossTonnage: 106000,
    yearBuilt: 2020,
    flag: 'Liberia',
    ownerId: 'own-oldendorff',
    ownerName: 'Oldendorff Carriers GmbH',
    ownerCountry: 'Germany',
    operatorId: 'op-oldendorff',
    operatorName: 'Oldendorff Commercial Desk',
    operatorCountry: 'Germany',
    fleetId: 'flt-oldendorff-dry',
    fleetName: 'Oldendorff Transoceanic Bulkers',
    cargoCategory: 'Dry Bulk',
    primaryCommodity: 'Carajas Iron Ore Fines',
    deployment: {
      region: 'Americas / US Gulf & Caribbean',
      country: 'Brazil',
      subArea: 'Ponta da Madeira Marine Terminal',
      latitude: -2.55,
      longitude: -44.38,
      status: 'loading',
      destinationPort: 'Rotterdam (NLRTM)',
      eta: '2026-09-27 18:00 UTC',
      speedKnots: 0.1,
      heading: 45,
    },
    ciiRating: 'A',
    dailyFuelConsumptionMt: 34.0,
  },
  {
    id: 107,
    name: 'GOLDEN CATHRINE',
    imoNumber: 'IMO 9811107',
    vesselClass: 'Capesize',
    vesselType: 'Capesize Bulk Carrier',
    dwt: 180000,
    grossTonnage: 94000,
    yearBuilt: 2019,
    flag: 'Marshall Islands',
    ownerId: 'own-goldenocean',
    ownerName: 'Golden Ocean Group Ltd',
    ownerCountry: 'Norway',
    operatorId: 'op-bhp',
    operatorName: 'BHP Marine Logistics',
    operatorCountry: 'Australia',
    fleetId: 'flt-goldenocean-bulk',
    fleetName: 'Golden Ocean Capesize Pool',
    cargoCategory: 'Dry Bulk',
    primaryCommodity: 'Newman Iron Ore Blend',
    deployment: {
      region: 'Southeast Asia',
      country: 'Indonesia',
      subArea: 'Lombok Strait Northbound Trench',
      latitude: -8.45,
      longitude: 115.8,
      status: 'underway',
      destinationPort: 'Caofeidian (CNCFD)',
      eta: '2026-09-22 08:00 UTC',
      speedKnots: 12.8,
      heading: 10,
    },
    ciiRating: 'B',
    dailyFuelConsumptionMt: 31.8,
  },

  // 3. Suezmax & Aframax Fleet
  {
    id: 108,
    name: 'CAP GUILLAUME',
    imoNumber: 'IMO 9388108',
    vesselClass: 'Suezmax',
    vesselType: 'Suezmax Crude Tanker',
    dwt: 158000,
    grossTonnage: 83000,
    yearBuilt: 2016,
    flag: 'Belgium',
    ownerId: 'own-euronav',
    ownerName: 'Euronav NV / CMB.TECH',
    ownerCountry: 'Belgium',
    operatorId: 'op-total',
    operatorName: 'TotalEnergies CSSA',
    operatorCountry: 'France',
    fleetId: 'flt-euronav-crude',
    fleetName: 'Euronav Global Crude Fleet',
    cargoCategory: 'Crude Oil',
    primaryCommodity: 'Forcados Blend Crude',
    deployment: {
      region: 'West & Southern Africa',
      country: 'Nigeria',
      subArea: 'Bonny Offshore Oil Terminal',
      latitude: 4.42,
      longitude: 7.15,
      status: 'loading',
      destinationPort: 'Le Havre (FRLEH)',
      eta: '2026-09-25 16:00 UTC',
      speedKnots: 0.1,
      heading: 190,
    },
    ciiRating: 'C',
    dailyFuelConsumptionMt: 35.2,
  },
  {
    id: 109,
    name: 'FRONT CASCADE',
    imoNumber: 'IMO 9822109',
    vesselClass: 'Suezmax',
    vesselType: 'Suezmax Crude Tanker',
    dwt: 157000,
    grossTonnage: 82500,
    yearBuilt: 2020,
    flag: 'Liberia',
    ownerId: 'own-frontline',
    ownerName: 'Frontline Ltd',
    ownerCountry: 'Norway',
    operatorId: 'op-vitol',
    operatorName: 'Vitol / Mansel Oil',
    operatorCountry: 'Netherlands',
    fleetId: 'flt-frontline-tankers',
    fleetName: 'Frontline Global Tankers',
    cargoCategory: 'Crude Oil',
    primaryCommodity: 'CPC Blend Crude',
    deployment: {
      region: 'Mediterranean & Black Sea',
      country: 'Greece',
      subArea: 'Ionian Sea Westbound',
      latitude: 37.5,
      longitude: 19.8,
      status: 'underway',
      destinationPort: 'Trieste (ITTRS)',
      eta: '2026-09-17 12:00 UTC',
      speedKnots: 13.5,
      heading: 325,
    },
    ciiRating: 'B',
    dailyFuelConsumptionMt: 33.4,
  },
  {
    id: 110,
    name: 'STI THUNDERBIRD',
    imoNumber: 'IMO 9711110',
    vesselClass: 'Aframax',
    vesselType: 'Aframax / LR2 Tanker',
    dwt: 115000,
    grossTonnage: 61000,
    yearBuilt: 2018,
    flag: 'Marshall Islands',
    ownerId: 'own-scorpio',
    ownerName: 'Scorpio Tankers Inc',
    ownerCountry: 'Monaco',
    operatorId: 'op-glencore',
    operatorName: 'ST Shipping / Glencore',
    operatorCountry: 'Switzerland',
    fleetId: 'flt-scorpio-products',
    fleetName: 'Scorpio Product & Clean Fleet',
    cargoCategory: 'Clean Petroleum Products',
    primaryCommodity: 'Ultra-Low Sulfur Diesel (ULSD)',
    deployment: {
      region: 'Northwest Europe & Baltic',
      country: 'Netherlands',
      subArea: 'Rotterdam Maasvlakte Quay Berth 4',
      latitude: 51.95,
      longitude: 4.05,
      status: 'discharging',
      destinationPort: 'Rotterdam (NLRTM)',
      eta: 'Arrived',
      speedKnots: 0.0,
      heading: 80,
    },
    ciiRating: 'B',
    dailyFuelConsumptionMt: 28.5,
  },

  // 4. LNG Gas Carrier Fleet
  {
    id: 111,
    name: 'AL GHARIYA',
    imoNumber: 'IMO 9383111',
    vesselClass: 'LNG Carrier',
    vesselType: 'Q-Flex LNG Carrier',
    dwt: 122000,
    grossTonnage: 136000,
    yearBuilt: 2021,
    flag: 'Qatar',
    ownerId: 'own-nakilat',
    ownerName: 'Nakilat Qatar Gas Transport',
    ownerCountry: 'Qatar',
    operatorId: 'op-shell',
    operatorName: 'Shell International Trading & Shipping',
    operatorCountry: 'United Kingdom',
    fleetId: 'flt-nakilat-lng',
    fleetName: 'Nakilat National LNG Fleet',
    cargoCategory: 'LNG Gas',
    primaryCommodity: 'Liquefied Natural Gas (216,000 m3)',
    deployment: {
      region: 'Middle East Gulf & Red Sea',
      country: 'Qatar',
      subArea: 'Ras Laffan LNG Berth 3',
      latitude: 25.92,
      longitude: 51.58,
      status: 'loading',
      destinationPort: 'Tokyo Bay (JPTYO)',
      eta: '2026-09-28 06:00 UTC',
      speedKnots: 0.1,
      heading: 90,
    },
    ciiRating: 'A',
    dailyFuelConsumptionMt: 36.0,
  },
  {
    id: 112,
    name: 'MARAN GAS APOLLONIA',
    imoNumber: 'IMO 9821112',
    vesselClass: 'LNG Carrier',
    vesselType: '174k m3 ME-GI LNG Carrier',
    dwt: 94000,
    grossTonnage: 114000,
    yearBuilt: 2023,
    flag: 'Greece',
    ownerId: 'own-maran',
    ownerName: 'Maran Gas & Maritime',
    ownerCountry: 'Greece',
    operatorId: 'op-total',
    operatorName: 'TotalEnergies CSSA',
    operatorCountry: 'France',
    fleetId: 'flt-maran-tankers',
    fleetName: 'Maran Strategic Energy Fleet',
    cargoCategory: 'LNG Gas',
    primaryCommodity: 'Liquefied Natural Gas (174,000 m3)',
    deployment: {
      region: 'Americas / US Gulf & Caribbean',
      country: 'USA',
      subArea: 'Sabine Pass LNG Channel',
      latitude: 29.75,
      longitude: -93.88,
      status: 'underway',
      destinationPort: 'Zeebrugge (BEZEE)',
      eta: '2026-09-24 14:00 UTC',
      speedKnots: 16.5,
      heading: 105,
    },
    ciiRating: 'A',
    dailyFuelConsumptionMt: 33.5,
  },

  // 5. VLGC LPG Fleet
  {
    id: 113,
    name: 'BW BALDER',
    imoNumber: 'IMO 9844113',
    vesselClass: 'VLGC LPG Carrier',
    vesselType: 'Very Large Gas Carrier (84k m3)',
    dwt: 55000,
    grossTonnage: 49000,
    yearBuilt: 2021,
    flag: 'Singapore',
    ownerId: 'own-bwgroup',
    ownerName: 'BW Group / BW LPG',
    ownerCountry: 'Singapore',
    operatorId: 'op-trafigura',
    operatorName: 'Trafigura Maritime Logistics',
    operatorCountry: 'Singapore',
    fleetId: 'flt-bw-lpg',
    fleetName: 'BW Oceanic Gas Transport',
    cargoCategory: 'LPG Gas',
    primaryCommodity: 'Refrigerated Propane / Butane',
    deployment: {
      region: 'Americas / US Gulf & Caribbean',
      country: 'Panama',
      subArea: 'Panama Canal Pacific Anchorage',
      latitude: 8.92,
      longitude: -79.52,
      status: 'anchored',
      destinationPort: 'Chiba (JPCHB)',
      eta: '2026-10-04 12:00 UTC',
      speedKnots: 0.2,
      heading: 160,
    },
    ciiRating: 'A',
    dailyFuelConsumptionMt: 26.5,
  },

  // 6. Panamax, Supramax & Handysize Dry Fleets
  {
    id: 114,
    name: 'STAR GEMINI',
    imoNumber: 'IMO 9642114',
    vesselClass: 'Panamax',
    vesselType: 'Kamsarmax Bulk Carrier',
    dwt: 82000,
    grossTonnage: 44000,
    yearBuilt: 2017,
    flag: 'Liberia',
    ownerId: 'own-starbulk',
    ownerName: 'Star Bulk Carriers Corp',
    ownerCountry: 'Greece',
    operatorId: 'op-cargill',
    operatorName: 'Cargill Ocean Transportation',
    operatorCountry: 'Switzerland',
    fleetId: 'flt-starbulk-capes',
    fleetName: 'Star Bulk Mineral Fleet',
    cargoCategory: 'Dry Bulk',
    primaryCommodity: 'US Gulf Soybeans in Bulk',
    deployment: {
      region: 'Americas / US Gulf & Caribbean',
      country: 'USA',
      subArea: 'Mississippi River Mile 110 Anchorage',
      latitude: 29.98,
      longitude: -90.25,
      status: 'loading',
      destinationPort: 'Qingdao (CNQDG)',
      eta: '2026-10-08 18:00 UTC',
      speedKnots: 0.1,
      heading: 130,
    },
    ciiRating: 'B',
    dailyFuelConsumptionMt: 22.0,
  },
  {
    id: 115,
    name: 'PACIFIC ENDEAVOUR',
    imoNumber: 'IMO 9711115',
    vesselClass: 'Handysize',
    vesselType: 'Geared Handysize Bulk Carrier',
    dwt: 38500,
    grossTonnage: 24000,
    yearBuilt: 2019,
    flag: 'Hong Kong',
    ownerId: 'own-pacbasin',
    ownerName: 'Pacific Basin Shipping Ltd',
    ownerCountry: 'Hong Kong',
    operatorId: 'op-pacbasin',
    operatorName: 'Pacific Basin Pool Management',
    operatorCountry: 'Hong Kong',
    fleetId: 'flt-pacbasin-handy',
    fleetName: 'Pacific Basin Handysize Fleet',
    cargoCategory: 'Dry Bulk',
    primaryCommodity: 'Australian Feed Barley',
    deployment: {
      region: 'Australia & Oceania',
      country: 'Australia',
      subArea: 'Fremantle Outer Harbour Anchorage',
      latitude: -32.05,
      longitude: 115.72,
      status: 'underway',
      destinationPort: 'Dammam (SADMM)',
      eta: '2026-09-27 10:00 UTC',
      speedKnots: 11.8,
      heading: 310,
    },
    ciiRating: 'A',
    dailyFuelConsumptionMt: 16.5,
  },
  {
    id: 116,
    name: 'STI BRIGHTON',
    imoNumber: 'IMO 9688116',
    vesselClass: 'MR Product Tanker',
    vesselType: 'Medium Range Product Tanker',
    dwt: 49990,
    grossTonnage: 29800,
    yearBuilt: 2016,
    flag: 'Marshall Islands',
    ownerId: 'own-scorpio',
    ownerName: 'Scorpio Tankers Inc',
    ownerCountry: 'Monaco',
    operatorId: 'op-trafigura',
    operatorName: 'Trafigura Maritime Logistics',
    operatorCountry: 'Singapore',
    fleetId: 'flt-scorpio-products',
    fleetName: 'Scorpio Product & Clean Fleet',
    cargoCategory: 'Clean Petroleum Products',
    primaryCommodity: 'Jet A-1 Aviation Kerosene',
    deployment: {
      region: 'Southeast Asia',
      country: 'Singapore',
      subArea: 'Jurong Island Oil Terminal Berth 6',
      latitude: 1.28,
      longitude: 103.7,
      status: 'discharging',
      destinationPort: 'Singapore (SGSIN)',
      eta: 'Arrived',
      speedKnots: 0.0,
      heading: 260,
    },
    ciiRating: 'B',
    dailyFuelConsumptionMt: 21.0,
  },
];

// Seed remaining 38 vessels to reach full 54 vessels across all classes, owners, and operators
const VESSEL_NAMES_POOL = [
  'NORDIC VOYAGER', 'FRONT ODYSSEY', 'DHT LOTUS', 'STAR POLARIS', 'LISA OLDENDORFF',
  'GOLDEN WAVE', 'PACIFIC MERIT', 'AL DEEBEL', 'BW OAK', 'STI DUCHESS', 'MARAN ARIES',
  'ANTWERPEN VENTURE', 'FRONT TIGER', 'DHT TIGER', 'STAR AQUILA', 'GEORG OLDENDORFF',
  'GOLDEN BREEZE', 'PACIFIC VENTURE', 'AL SADD', 'BW ELM', 'STI POPPY', 'MARAN LEO',
  'EURO VOYAGER', 'FRONT LEOPARD', 'DHT SCORPIO', 'STAR SIRIUS', 'KARL OLDENDORFF',
  'GOLDEN HORIZON', 'PACIFIC HARMONY', 'AL WAKRAH', 'BW CEDAR', 'STI ROSE', 'MARAN GEMINI',
  'FLANDERS PIONEER', 'FRONT JAGUAR', 'DHT TAURUS', 'STAR VEGA', 'OTTO OLDENDORFF',
];

const REGIONS_POOL = [
  { region: 'Asia-Pacific / Far East', country: 'China', subArea: 'Bohai Bay Offshore Anchorage', lat: 38.5, lng: 118.8 },
  { region: 'Asia-Pacific / Far East', country: 'Japan', subArea: 'Tokyo Bay Entrance Channel', lat: 35.25, lng: 139.75 },
  { region: 'Southeast Asia', country: 'Singapore', subArea: 'Eastern Anchorage Sector B', lat: 1.28, lng: 103.88 },
  { region: 'Southeast Asia', country: 'Malaysia', subArea: 'Port Klang Fairway Channel', lat: 2.95, lng: 101.35 },
  { region: 'Middle East Gulf & Red Sea', country: 'UAE', subArea: 'Fujairah Offshore Bunker Zone', lat: 25.18, lng: 56.45 },
  { region: 'Middle East Gulf & Red Sea', country: 'Saudi Arabia', subArea: 'Jubail Industrial Port Approach', lat: 27.05, lng: 49.75 },
  { region: 'Northwest Europe & Baltic', country: 'Germany', subArea: 'Elbe River Approach to Hamburg', lat: 53.9, lng: 8.85 },
  { region: 'Northwest Europe & Baltic', country: 'United Kingdom', subArea: 'Thames Estuary Outer Anchorage', lat: 51.5, lng: 1.2 },
  { region: 'Mediterranean & Black Sea', country: 'Italy', subArea: 'Genoa Outer Breakwater Anchorage', lat: 44.38, lng: 8.92 },
  { region: 'Mediterranean & Black Sea', country: 'Spain', subArea: 'Gibraltar Bay Bunkering Area', lat: 36.15, lng: -5.38 },
  { region: 'Americas / US Gulf & Caribbean', country: 'USA', subArea: 'Houston Ship Channel Anchorage', lat: 29.35, lng: -94.75 },
  { region: 'Americas / US Gulf & Caribbean', country: 'Panama', subArea: 'Cristobal Atlantic Anchorage', lat: 9.38, lng: -79.92 },
  { region: 'Australia & Oceania', country: 'Australia', subArea: 'Dampier Cargo Terminal Approach', lat: -20.65, lng: 116.7 },
  { region: 'Australia & Oceania', country: 'Australia', subArea: 'Gladstone Bauxite Channel', lat: -23.85, lng: 151.3 },
  { region: 'West & Southern Africa', country: 'South Africa', subArea: 'Saldanha Bay Iron Ore Anchorage', lat: -33.05, lng: 17.95 },
  { region: 'West & Southern Africa', country: 'Angola', subArea: 'Luanda Offshore FPSO Complex', lat: -8.75, lng: 13.25 },
];

const CLASSES_POOL: Array<{ class: FleetVesselRecord['vesselClass']; type: string; cat: FleetVesselRecord['cargoCategory']; dwt: number }> = [
  { class: 'Capesize', type: 'Capesize Bulk Carrier', cat: 'Dry Bulk', dwt: 181000 },
  { class: 'Panamax', type: 'Kamsarmax Bulk Carrier', cat: 'Dry Bulk', dwt: 82500 },
  { class: 'Supramax', type: 'Ultramax Bulk Carrier', cat: 'Dry Bulk', dwt: 63000 },
  { class: 'Handysize', type: 'Geared Handysize Bulker', cat: 'Dry Bulk', dwt: 38000 },
  { class: 'VLCC', type: 'Very Large Crude Carrier', cat: 'Crude Oil', dwt: 305000 },
  { class: 'Suezmax', type: 'Suezmax Crude Tanker', cat: 'Crude Oil', dwt: 157000 },
  { class: 'Aframax', type: 'Aframax / LR2 Tanker', cat: 'Clean Petroleum Products', dwt: 112000 },
  { class: 'MR Product Tanker', type: 'Medium Range Product Tanker', cat: 'Clean Petroleum Products', dwt: 49990 },
  { class: 'LNG Carrier', type: '174k m3 LNG Carrier', cat: 'LNG Gas', dwt: 95000 },
  { class: 'VLGC LPG Carrier', type: 'Very Large Gas Carrier', cat: 'LPG Gas', dwt: 56000 },
];

for (let i = 0; i < VESSEL_NAMES_POOL.length; i++) {
  const vId = 117 + i;
  const name = VESSEL_NAMES_POOL[i];
  const spec = CLASSES_POOL[i % CLASSES_POOL.length];
  const loc = REGIONS_POOL[i % REGIONS_POOL.length];
  const owner = OWNERS_REGISTRY[i % OWNERS_REGISTRY.length];
  const operator = OPERATORS_REGISTRY[i % OPERATORS_REGISTRY.length];
  const year = 2015 + (i % 9);
  const status: FleetVesselRecord['deployment']['status'] =
    i % 5 === 0 ? 'loading' : i % 5 === 1 ? 'discharging' : i % 5 === 2 ? 'anchored' : 'underway';

  FLEET_VESSELS_REGISTRY.push({
    id: vId,
    name,
    imoNumber: `IMO 9${vId.toString().padStart(6, '0')}`,
    vesselClass: spec.class,
    vesselType: spec.type,
    dwt: spec.dwt,
    grossTonnage: Math.round(spec.dwt * 0.55),
    yearBuilt: year,
    flag: i % 2 === 0 ? 'Marshall Islands' : i % 3 === 0 ? 'Liberia' : 'Singapore',
    ownerId: owner.id,
    ownerName: owner.name,
    ownerCountry: owner.country,
    operatorId: operator.id,
    operatorName: operator.name,
    operatorCountry: operator.country,
    fleetId: `flt-${owner.id.replace('own-', '')}`,
    fleetName: `${owner.name.split(' ')[0]} Strategic Fleet`,
    cargoCategory: spec.cat,
    primaryCommodity:
      spec.cat === 'Dry Bulk'
        ? 'Iron Ore / Metallurgical Coal'
        : spec.cat === 'Crude Oil'
        ? 'Heavy Crude Oil'
        : spec.cat === 'Clean Petroleum Products'
        ? 'Gasoline / Jet Fuel'
        : spec.cat === 'LNG Gas'
        ? 'Liquefied Natural Gas'
        : 'Liquefied Petroleum Gas',
    deployment: {
      region: loc.region,
      country: loc.country,
      subArea: loc.subArea,
      latitude: parseFloat((loc.lat + (i * 0.05 - 0.2)).toFixed(4)),
      longitude: parseFloat((loc.lng + (i * 0.08 - 0.3)).toFixed(4)),
      status,
      destinationPort: 'Singapore (SGSIN)',
      eta: '2026-09-26 12:00 UTC',
      speedKnots: status === 'underway' ? 12.5 + (i % 3) : 0.1,
      heading: (i * 35) % 360,
    },
    ciiRating: (['A', 'B', 'C', 'D'][i % 4] as 'A' | 'B' | 'C' | 'D'),
    dailyFuelConsumptionMt: parseFloat((spec.dwt / 8000 + 10).toFixed(1)),
  });
}
