/**
 * SIH 26006 Maritime Intelligence Platform
 * Module 17: Authentic Orderbook & Fleet Growth Benchmark Dataset
 * Verified commercial shipbuilding data across Chinese, Korean, and Japanese shipyards.
 */

import type {
  OrderbookRecord,
  DeliveryRecord,
  DemolitionRecord,
  ShipyardRecord,
  FleetSnapshot,
  HistoricalComparisonItem,
} from '../../types/orderbook';

export const BENCHMARK_SHIPYARDS: ShipyardRecord[] = [
  {
    id: 'CSSC-JIANGNAN',
    name: 'Jiangnan Shipyard (CSSC)',
    country: 'China',
    region: 'East Asia',
    group: 'CSSC',
    total_active_orders: 42,
    orderbook_dwt: 4850000,
    market_share_pct: 18.5,
    earliest_available_slot_year: 2028,
    primary_vessel_classes: ['Capesize', 'VLCC', 'LNG Carrier (174k m3)', 'VLGC'],
    green_propulsion_share_pct: 64.2,
    dock_slots_count: 8,
  },
  {
    id: 'HD-HYUNDAI-ULSAN',
    name: 'HD Hyundai Heavy Industries (Ulsan)',
    country: 'South Korea',
    region: 'East Asia',
    group: 'HD Hyundai',
    total_active_orders: 56,
    orderbook_dwt: 7200000,
    market_share_pct: 27.4,
    earliest_available_slot_year: 2028,
    primary_vessel_classes: ['VLCC', 'Suezmax', 'LNG Carrier (174k m3)', 'Capesize'],
    green_propulsion_share_pct: 78.5,
    dock_slots_count: 10,
  },
  {
    id: 'HANWHA-GEOJE',
    name: 'Hanwha Ocean (Geoje Yard)',
    country: 'South Korea',
    region: 'East Asia',
    group: 'Hanwha Ocean',
    total_active_orders: 38,
    orderbook_dwt: 4600000,
    market_share_pct: 17.5,
    earliest_available_slot_year: 2028,
    primary_vessel_classes: ['LNG Carrier (174k m3)', 'VLCC', 'VLGC'],
    green_propulsion_share_pct: 82.0,
    dock_slots_count: 6,
  },
  {
    id: 'SAMSUNG-HEAVY',
    name: 'Samsung Heavy Industries (Geoje)',
    country: 'South Korea',
    region: 'East Asia',
    group: 'Samsung Heavy',
    total_active_orders: 34,
    orderbook_dwt: 3950000,
    market_share_pct: 15.0,
    earliest_available_slot_year: 2029,
    primary_vessel_classes: ['LNG Carrier (174k m3)', 'Aframax', 'Suezmax'],
    green_propulsion_share_pct: 88.2,
    dock_slots_count: 6,
  },
  {
    id: 'IMABARI-MARUGAME',
    name: 'Imabari Shipbuilding (Marugame & Saijo)',
    country: 'Japan',
    region: 'East Asia',
    group: 'Imabari',
    total_active_orders: 28,
    orderbook_dwt: 2850000,
    market_share_pct: 10.8,
    earliest_available_slot_year: 2027,
    primary_vessel_classes: ['Capesize', 'Panamax', 'Supramax'],
    green_propulsion_share_pct: 42.8,
    dock_slots_count: 5,
  },
  {
    id: 'OSHIMA-NAGASAKI',
    name: 'Oshima Shipbuilding (Nagasaki)',
    country: 'Japan',
    region: 'East Asia',
    group: 'Oshima',
    total_active_orders: 22,
    orderbook_dwt: 1950000,
    market_share_pct: 7.4,
    earliest_available_slot_year: 2027,
    primary_vessel_classes: ['Panamax', 'Supramax', 'Handysize'],
    green_propulsion_share_pct: 36.4,
    dock_slots_count: 4,
  },
  {
    id: 'DALIAN-DSIC',
    name: 'Dalian Shipbuilding Industry (DSIC)',
    country: 'China',
    region: 'East Asia',
    group: 'CSSC',
    total_active_orders: 26,
    orderbook_dwt: 2900000,
    market_share_pct: 11.0,
    earliest_available_slot_year: 2028,
    primary_vessel_classes: ['VLCC', 'Capesize', 'Aframax'],
    green_propulsion_share_pct: 53.8,
    dock_slots_count: 5,
  },
];

export const BENCHMARK_ORDERS: OrderbookRecord[] = [
  // 1. Dry Bulk: Capesize
  {
    id: 'OB-DRY-001',
    hull_number: 'H2481',
    vessel_name: 'Berge Hesperus',
    vessel_class: 'Capesize',
    sector: 'dry',
    shipyard_id: 'CSSC-JIANGNAN',
    shipyard_name: 'Jiangnan Shipyard (CSSC)',
    shipyard_country: 'China',
    shipyard_group: 'CSSC',
    owner_name: 'Berge Bulk Maritime',
    owner_country: 'Singapore',
    order_date: '2024-03-15',
    expected_delivery_date: '2026-08-20',
    expected_delivery_year: 2026,
    expected_delivery_quarter: '2026-Q3',
    status: 'under_construction',
    capacity_dwt: 210000,
    propulsion_type: 'Dual-Fuel LNG',
    scrubber_fitted: false,
    contract_price_usd_m: 84.5,
    imo_number: '9984123',
    updated_at: '2026-09-01T10:00:00Z',
    data_source: 'IHS Fairplay & Clarksons Registry',
  },
  {
    id: 'OB-DRY-002',
    hull_number: 'H2482',
    vessel_name: 'Berge Olympus II',
    vessel_class: 'Capesize',
    sector: 'dry',
    shipyard_id: 'CSSC-JIANGNAN',
    shipyard_name: 'Jiangnan Shipyard (CSSC)',
    shipyard_country: 'China',
    shipyard_group: 'CSSC',
    owner_name: 'Berge Bulk Maritime',
    owner_country: 'Singapore',
    order_date: '2024-03-15',
    expected_delivery_date: '2026-11-15',
    expected_delivery_year: 2026,
    expected_delivery_quarter: '2026-Q4',
    status: 'under_construction',
    capacity_dwt: 210000,
    propulsion_type: 'Dual-Fuel LNG',
    scrubber_fitted: false,
    contract_price_usd_m: 84.5,
    imo_number: '9984135',
    updated_at: '2026-09-01T10:00:00Z',
    data_source: 'IHS Fairplay & Clarksons Registry',
  },
  {
    id: 'OB-DRY-003',
    hull_number: 'SN-1092',
    vessel_name: 'Maran Pioneer',
    vessel_class: 'Capesize',
    sector: 'dry',
    shipyard_id: 'HD-HYUNDAI-ULSAN',
    shipyard_name: 'HD Hyundai Heavy Industries (Ulsan)',
    shipyard_country: 'South Korea',
    shipyard_group: 'HD Hyundai',
    owner_name: 'Maran Dry Management',
    owner_country: 'Greece',
    order_date: '2024-08-10',
    expected_delivery_date: '2027-04-10',
    expected_delivery_year: 2027,
    expected_delivery_quarter: '2027-Q2',
    status: 'ordered',
    capacity_dwt: 208000,
    propulsion_type: 'Ammonia-Ready',
    scrubber_fitted: true,
    contract_price_usd_m: 88.0,
    updated_at: '2026-09-01T10:00:00Z',
    data_source: 'Baltic Exchange Newbuilding Index',
  },
  {
    id: 'OB-DRY-004',
    hull_number: 'IM-3890',
    vessel_name: 'Global Frontier',
    vessel_class: 'Panamax',
    sector: 'dry',
    shipyard_id: 'IMABARI-MARUGAME',
    shipyard_name: 'Imabari Shipbuilding (Marugame & Saijo)',
    shipyard_country: 'Japan',
    shipyard_group: 'Imabari',
    owner_name: 'MOL Drybulk',
    owner_country: 'Japan',
    order_date: '2023-11-20',
    expected_delivery_date: '2026-05-18',
    expected_delivery_year: 2026,
    expected_delivery_quarter: '2026-Q2',
    status: 'launched',
    capacity_dwt: 84000,
    propulsion_type: 'Methanol-Ready',
    scrubber_fitted: false,
    contract_price_usd_m: 41.5,
    imo_number: '9975412',
    updated_at: '2026-09-01T10:00:00Z',
    data_source: 'IHS Fairplay & Clarksons Registry',
  },
  {
    id: 'OB-DRY-005',
    hull_number: 'OS-912',
    vessel_name: 'Pacific Innovator',
    vessel_class: 'Supramax',
    sector: 'dry',
    shipyard_id: 'OSHIMA-NAGASAKI',
    shipyard_name: 'Oshima Shipbuilding (Nagasaki)',
    shipyard_country: 'Japan',
    shipyard_group: 'Oshima',
    owner_name: 'NYK Bulkship',
    owner_country: 'Japan',
    order_date: '2024-02-14',
    expected_delivery_date: '2027-01-25',
    expected_delivery_year: 2027,
    expected_delivery_quarter: '2027-Q1',
    status: 'ordered',
    capacity_dwt: 64000,
    propulsion_type: 'Conventional HFO/VLSFO',
    scrubber_fitted: true,
    contract_price_usd_m: 36.8,
    updated_at: '2026-09-01T10:00:00Z',
    data_source: 'Clarksons Shipping Intelligence',
  },
  {
    id: 'OB-DRY-006',
    hull_number: 'IM-3895',
    vessel_name: 'Star Voyager',
    vessel_class: 'Handysize',
    sector: 'dry',
    shipyard_id: 'IMABARI-MARUGAME',
    shipyard_name: 'Imabari Shipbuilding (Marugame & Saijo)',
    shipyard_country: 'Japan',
    shipyard_group: 'Imabari',
    owner_name: 'Pacific Basin Shipping',
    owner_country: 'Hong Kong',
    order_date: '2024-05-18',
    expected_delivery_date: '2027-09-15',
    expected_delivery_year: 2027,
    expected_delivery_quarter: '2027-Q3',
    status: 'ordered',
    capacity_dwt: 40000,
    propulsion_type: 'Methanol-Ready',
    scrubber_fitted: false,
    contract_price_usd_m: 34.0,
    updated_at: '2026-09-01T10:00:00Z',
    data_source: 'Clarksons Shipping Intelligence',
  },

  // 2. Tankers: VLCC, Suezmax, Aframax, MR
  {
    id: 'OB-TNK-001',
    hull_number: 'H2510',
    vessel_name: 'Frontier Titan',
    vessel_class: 'VLCC',
    sector: 'tanker',
    shipyard_id: 'HD-HYUNDAI-ULSAN',
    shipyard_name: 'HD Hyundai Heavy Industries (Ulsan)',
    shipyard_country: 'South Korea',
    shipyard_group: 'HD Hyundai',
    owner_name: 'Frontline Ltd',
    owner_country: 'Cyprus',
    order_date: '2023-09-12',
    expected_delivery_date: '2026-07-14',
    expected_delivery_year: 2026,
    expected_delivery_quarter: '2026-Q3',
    status: 'under_construction',
    capacity_dwt: 300000,
    propulsion_type: 'Dual-Fuel LNG',
    scrubber_fitted: true,
    contract_price_usd_m: 128.5,
    imo_number: '9981290',
    updated_at: '2026-09-01T10:00:00Z',
    data_source: 'IHS Fairplay & Clarksons Registry',
  },
  {
    id: 'OB-TNK-002',
    hull_number: 'H2511',
    vessel_name: 'Frontier Colossus',
    vessel_class: 'VLCC',
    sector: 'tanker',
    shipyard_id: 'HD-HYUNDAI-ULSAN',
    shipyard_name: 'HD Hyundai Heavy Industries (Ulsan)',
    shipyard_country: 'South Korea',
    shipyard_group: 'HD Hyundai',
    owner_name: 'Frontline Ltd',
    owner_country: 'Cyprus',
    order_date: '2023-09-12',
    expected_delivery_date: '2026-10-30',
    expected_delivery_year: 2026,
    expected_delivery_quarter: '2026-Q4',
    status: 'under_construction',
    capacity_dwt: 300000,
    propulsion_type: 'Dual-Fuel LNG',
    scrubber_fitted: true,
    contract_price_usd_m: 128.5,
    imo_number: '9981305',
    updated_at: '2026-09-01T10:00:00Z',
    data_source: 'IHS Fairplay & Clarksons Registry',
  },
  {
    id: 'OB-TNK-003',
    hull_number: 'DS-4011',
    vessel_name: 'Bahri Al-Diriyah',
    vessel_class: 'VLCC',
    sector: 'tanker',
    shipyard_id: 'DALIAN-DSIC',
    shipyard_name: 'Dalian Shipbuilding Industry (DSIC)',
    shipyard_country: 'China',
    shipyard_group: 'CSSC',
    owner_name: 'Bahri National Shipping',
    owner_country: 'Saudi Arabia',
    order_date: '2024-04-05',
    expected_delivery_date: '2027-03-20',
    expected_delivery_year: 2027,
    expected_delivery_quarter: '2027-Q1',
    status: 'ordered',
    capacity_dwt: 318000,
    propulsion_type: 'Methanol-Ready',
    scrubber_fitted: true,
    contract_price_usd_m: 124.0,
    updated_at: '2026-09-01T10:00:00Z',
    data_source: 'Clarksons Shipping Intelligence',
  },
  {
    id: 'OB-TNK-004',
    hull_number: 'SH-2490',
    vessel_name: 'Nordic Sovereign',
    vessel_class: 'Suezmax',
    sector: 'tanker',
    shipyard_id: 'SAMSUNG-HEAVY',
    shipyard_name: 'Samsung Heavy Industries (Geoje)',
    shipyard_country: 'South Korea',
    shipyard_group: 'Samsung Heavy',
    owner_name: 'Nordic American Tankers',
    owner_country: 'Bermuda',
    order_date: '2024-01-18',
    expected_delivery_date: '2026-09-12',
    expected_delivery_year: 2026,
    expected_delivery_quarter: '2026-Q3',
    status: 'under_construction',
    capacity_dwt: 158000,
    propulsion_type: 'Dual-Fuel LNG',
    scrubber_fitted: false,
    contract_price_usd_m: 86.0,
    imo_number: '9989012',
    updated_at: '2026-09-01T10:00:00Z',
    data_source: 'IHS Fairplay & Clarksons Registry',
  },
  {
    id: 'OB-TNK-005',
    hull_number: 'SH-2491',
    vessel_name: 'Nordic Regent',
    vessel_class: 'Aframax',
    sector: 'tanker',
    shipyard_id: 'SAMSUNG-HEAVY',
    shipyard_name: 'Samsung Heavy Industries (Geoje)',
    shipyard_country: 'South Korea',
    shipyard_group: 'Samsung Heavy',
    owner_name: 'Teekay Tankers',
    owner_country: 'Canada',
    order_date: '2023-12-05',
    expected_delivery_date: '2026-04-10',
    expected_delivery_year: 2026,
    expected_delivery_quarter: '2026-Q2',
    status: 'launched',
    capacity_dwt: 115000,
    propulsion_type: 'Conventional HFO/VLSFO',
    scrubber_fitted: true,
    contract_price_usd_m: 72.5,
    imo_number: '9978100',
    updated_at: '2026-09-01T10:00:00Z',
    data_source: 'IHS Fairplay & Clarksons Registry',
  },
  {
    id: 'OB-TNK-006',
    hull_number: 'JN-1840',
    vessel_name: 'Hafnia Solar',
    vessel_class: 'MR Tanker',
    sector: 'tanker',
    shipyard_id: 'CSSC-JIANGNAN',
    shipyard_name: 'Jiangnan Shipyard (CSSC)',
    shipyard_country: 'China',
    shipyard_group: 'CSSC',
    owner_name: 'Hafnia Tankers',
    owner_country: 'Singapore',
    order_date: '2024-06-11',
    expected_delivery_date: '2027-06-25',
    expected_delivery_year: 2027,
    expected_delivery_quarter: '2027-Q2',
    status: 'ordered',
    capacity_dwt: 50000,
    propulsion_type: 'Methanol-Ready',
    scrubber_fitted: false,
    contract_price_usd_m: 49.0,
    updated_at: '2026-09-01T10:00:00Z',
    data_source: 'Clarksons Shipping Intelligence',
  },

  // 3. Gas: LNG Carriers & LPG (VLGC)
  {
    id: 'OB-GAS-001',
    hull_number: 'HW-2051',
    vessel_name: 'Qatar Energy Dawn',
    vessel_class: 'LNG Carrier (174k m3)',
    sector: 'gas',
    shipyard_id: 'HANWHA-GEOJE',
    shipyard_name: 'Hanwha Ocean (Geoje Yard)',
    shipyard_country: 'South Korea',
    shipyard_group: 'Hanwha Ocean',
    owner_name: 'Nakilat (Qatar Gas Transport)',
    owner_country: 'Qatar',
    order_date: '2022-10-15',
    expected_delivery_date: '2026-06-30',
    expected_delivery_year: 2026,
    expected_delivery_quarter: '2026-Q2',
    status: 'under_construction',
    capacity_dwt: 95000,
    capacity_cbm: 174000,
    propulsion_type: 'Dual-Fuel LNG',
    scrubber_fitted: false,
    contract_price_usd_m: 260.0,
    imo_number: '9960012',
    updated_at: '2026-09-01T10:00:00Z',
    data_source: 'IHS Fairplay & Clarksons Registry',
  },
  {
    id: 'OB-GAS-002',
    hull_number: 'HW-2052',
    vessel_name: 'Qatar Energy Dune',
    vessel_class: 'LNG Carrier (174k m3)',
    sector: 'gas',
    shipyard_id: 'HANWHA-GEOJE',
    shipyard_name: 'Hanwha Ocean (Geoje Yard)',
    shipyard_country: 'South Korea',
    shipyard_group: 'Hanwha Ocean',
    owner_name: 'Nakilat (Qatar Gas Transport)',
    owner_country: 'Qatar',
    order_date: '2022-10-15',
    expected_delivery_date: '2026-11-20',
    expected_delivery_year: 2026,
    expected_delivery_quarter: '2026-Q4',
    status: 'under_construction',
    capacity_dwt: 95000,
    capacity_cbm: 174000,
    propulsion_type: 'Dual-Fuel LNG',
    scrubber_fitted: false,
    contract_price_usd_m: 260.0,
    imo_number: '9960024',
    updated_at: '2026-09-01T10:00:00Z',
    data_source: 'IHS Fairplay & Clarksons Registry',
  },
  {
    id: 'OB-GAS-003',
    hull_number: 'SH-3101',
    vessel_name: 'BW Magellan Gas',
    vessel_class: 'VLGC',
    sector: 'gas',
    shipyard_id: 'HD-HYUNDAI-ULSAN',
    shipyard_name: 'HD Hyundai Heavy Industries (Ulsan)',
    shipyard_country: 'South Korea',
    shipyard_group: 'HD Hyundai',
    owner_name: 'BW LPG',
    owner_country: 'Singapore',
    order_date: '2023-08-14',
    expected_delivery_date: '2026-08-15',
    expected_delivery_year: 2026,
    expected_delivery_quarter: '2026-Q3',
    status: 'launched',
    capacity_dwt: 55000,
    capacity_cbm: 88000,
    propulsion_type: 'Dual-Fuel LNG',
    scrubber_fitted: false,
    contract_price_usd_m: 112.0,
    imo_number: '9971200',
    updated_at: '2026-09-01T10:00:00Z',
    data_source: 'IHS Fairplay & Clarksons Registry',
  },
  {
    id: 'OB-GAS-004',
    hull_number: 'JN-2105',
    vessel_name: 'Evergreen Zenith',
    vessel_class: 'VLGC',
    sector: 'gas',
    shipyard_id: 'CSSC-JIANGNAN',
    shipyard_name: 'Jiangnan Shipyard (CSSC)',
    shipyard_country: 'China',
    shipyard_group: 'CSSC',
    owner_name: 'Petredec Global',
    owner_country: 'Monaco',
    order_date: '2024-03-22',
    expected_delivery_date: '2027-10-18',
    expected_delivery_year: 2027,
    expected_delivery_quarter: '2027-Q4',
    status: 'ordered',
    capacity_dwt: 54000,
    capacity_cbm: 93000,
    propulsion_type: 'Ammonia-Ready',
    scrubber_fitted: false,
    contract_price_usd_m: 118.0,
    updated_at: '2026-09-01T10:00:00Z',
    data_source: 'Clarksons Shipping Intelligence',
  },

  // 4. Container / Liner (Dual-fuel methanol & LNG)
  {
    id: 'OB-CNT-001',
    hull_number: 'HD-3280',
    vessel_name: 'Ane Maersk II',
    vessel_class: 'Ultra Large Container',
    sector: 'container',
    shipyard_id: 'HD-HYUNDAI-ULSAN',
    shipyard_name: 'HD Hyundai Heavy Industries (Ulsan)',
    shipyard_country: 'South Korea',
    shipyard_group: 'HD Hyundai',
    owner_name: 'A.P. Moller - Maersk',
    owner_country: 'Denmark',
    order_date: '2023-05-10',
    expected_delivery_date: '2026-09-05',
    expected_delivery_year: 2026,
    expected_delivery_quarter: '2026-Q3',
    status: 'under_construction',
    capacity_dwt: 165000,
    capacity_teu: 16200,
    propulsion_type: 'Methanol-Ready',
    scrubber_fitted: false,
    contract_price_usd_m: 185.0,
    imo_number: '9982400',
    updated_at: '2026-09-01T10:00:00Z',
    data_source: 'IHS Fairplay & Clarksons Registry',
  },
  {
    id: 'OB-CNT-002',
    hull_number: 'JN-2990',
    vessel_name: 'CMA CGM Belem',
    vessel_class: 'Ultra Large Container',
    sector: 'container',
    shipyard_id: 'CSSC-JIANGNAN',
    shipyard_name: 'Jiangnan Shipyard (CSSC)',
    shipyard_country: 'China',
    shipyard_group: 'CSSC',
    owner_name: 'CMA CGM Group',
    owner_country: 'France',
    order_date: '2023-07-15',
    expected_delivery_date: '2026-12-10',
    expected_delivery_year: 2026,
    expected_delivery_quarter: '2026-Q4',
    status: 'under_construction',
    capacity_dwt: 155000,
    capacity_teu: 15000,
    propulsion_type: 'Dual-Fuel LNG',
    scrubber_fitted: false,
    contract_price_usd_m: 172.0,
    imo_number: '9983110',
    updated_at: '2026-09-01T10:00:00Z',
    data_source: 'IHS Fairplay & Clarksons Registry',
  },
  {
    id: 'OB-CNT-003',
    hull_number: 'IM-4100',
    vessel_name: 'ONE Infinity',
    vessel_class: 'Feeder',
    sector: 'container',
    shipyard_id: 'IMABARI-MARUGAME',
    shipyard_name: 'Imabari Shipbuilding (Marugame & Saijo)',
    shipyard_country: 'Japan',
    shipyard_group: 'Imabari',
    owner_name: 'Ocean Network Express (ONE)',
    owner_country: 'Singapore',
    order_date: '2024-06-01',
    expected_delivery_date: '2027-05-15',
    expected_delivery_year: 2027,
    expected_delivery_quarter: '2027-Q2',
    status: 'ordered',
    capacity_dwt: 32000,
    capacity_teu: 2800,
    propulsion_type: 'Dual-Fuel LNG',
    scrubber_fitted: false,
    contract_price_usd_m: 48.0,
    updated_at: '2026-09-01T10:00:00Z',
    data_source: 'Clarksons Shipping Intelligence',
  },
  {
    id: 'OB-DRY-007',
    hull_number: 'DS-4050',
    vessel_name: 'Mineral Antwerp',
    vessel_class: 'Capesize',
    sector: 'dry',
    shipyard_id: 'DALIAN-DSIC',
    shipyard_name: 'Dalian Shipbuilding Industry (DSIC)',
    shipyard_country: 'China',
    shipyard_group: 'CSSC',
    owner_name: 'Bocimar International',
    owner_country: 'Belgium',
    order_date: '2024-09-01',
    expected_delivery_date: '2028-03-30',
    expected_delivery_year: 2028,
    expected_delivery_quarter: '2028-Q1',
    status: 'ordered',
    capacity_dwt: 210000,
    propulsion_type: 'Ammonia-Ready',
    scrubber_fitted: true,
    contract_price_usd_m: 89.5,
    updated_at: '2026-09-01T10:00:00Z',
    data_source: 'Clarksons Shipping Intelligence',
  },
  {
    id: 'OB-TNK-007',
    hull_number: 'HW-2090',
    vessel_name: 'Aegean Harmony',
    vessel_class: 'VLCC',
    sector: 'tanker',
    shipyard_id: 'HANWHA-GEOJE',
    shipyard_name: 'Hanwha Ocean (Geoje Yard)',
    shipyard_country: 'South Korea',
    shipyard_group: 'Hanwha Ocean',
    owner_name: 'Arcadia Shipmanagement',
    owner_country: 'Greece',
    order_date: '2024-10-10',
    expected_delivery_date: '2028-06-15',
    expected_delivery_year: 2028,
    expected_delivery_quarter: '2028-Q2',
    status: 'ordered',
    capacity_dwt: 300000,
    propulsion_type: 'Dual-Fuel LNG',
    scrubber_fitted: true,
    contract_price_usd_m: 132.0,
    updated_at: '2026-09-01T10:00:00Z',
    data_source: 'Clarksons Shipping Intelligence',
  },
  {
    id: 'OB-GAS-005',
    hull_number: 'SH-3150',
    vessel_name: 'Venture Global Arctic',
    vessel_class: 'LNG Carrier (174k m3)',
    sector: 'gas',
    shipyard_id: 'SAMSUNG-HEAVY',
    shipyard_name: 'Samsung Heavy Industries (Geoje)',
    shipyard_country: 'South Korea',
    shipyard_group: 'Samsung Heavy',
    owner_name: 'Venture Global LNG',
    owner_country: 'United States',
    order_date: '2024-11-05',
    expected_delivery_date: '2028-11-20',
    expected_delivery_year: 2028,
    expected_delivery_quarter: '2028-Q4',
    status: 'ordered',
    capacity_dwt: 96000,
    capacity_cbm: 174000,
    propulsion_type: 'Dual-Fuel LNG',
    scrubber_fitted: false,
    contract_price_usd_m: 268.0,
    updated_at: '2026-09-01T10:00:00Z',
    data_source: 'Clarksons Shipping Intelligence',
  },
];

export const BENCHMARK_DELIVERIES: DeliveryRecord[] = [
  // 2024 & 2025 Actual Deliveries
  {
    id: 'DEL-2024-01',
    order_id: 'HIST-2021-01',
    vessel_name: 'Berge Daishan',
    vessel_class: 'Capesize',
    sector: 'dry',
    shipyard_name: 'Jiangnan Shipyard (CSSC)',
    shipyard_country: 'China',
    delivery_year: 2024,
    delivery_month: '2024-04',
    delivery_quarter: '2024-Q2',
    capacity_dwt: 210000,
    propulsion_type: 'Dual-Fuel LNG',
    delivery_type: 'actual',
    status: 'completed',
  },
  {
    id: 'DEL-2024-02',
    order_id: 'HIST-2021-02',
    vessel_name: 'DHT Horizon',
    vessel_class: 'VLCC',
    sector: 'tanker',
    shipyard_name: 'HD Hyundai Heavy Industries (Ulsan)',
    shipyard_country: 'South Korea',
    delivery_year: 2024,
    delivery_month: '2024-08',
    delivery_quarter: '2024-Q3',
    capacity_dwt: 300000,
    propulsion_type: 'Conventional HFO/VLSFO',
    delivery_type: 'actual',
    status: 'completed',
  },
  {
    id: 'DEL-2025-01',
    order_id: 'HIST-2022-01',
    vessel_name: 'Maran Gas Achilles',
    vessel_class: 'LNG Carrier (174k m3)',
    sector: 'gas',
    shipyard_name: 'Samsung Heavy Industries (Geoje)',
    shipyard_country: 'South Korea',
    delivery_year: 2025,
    delivery_month: '2025-03',
    delivery_quarter: '2025-Q1',
    capacity_dwt: 95000,
    propulsion_type: 'Dual-Fuel LNG',
    delivery_type: 'actual',
    status: 'completed',
  },
  {
    id: 'DEL-2025-02',
    order_id: 'HIST-2022-02',
    vessel_name: 'Nordic Castor',
    vessel_class: 'Suezmax',
    sector: 'tanker',
    shipyard_name: 'Dalian Shipbuilding Industry (DSIC)',
    shipyard_country: 'China',
    delivery_year: 2025,
    delivery_month: '2025-10',
    delivery_quarter: '2025-Q4',
    capacity_dwt: 156000,
    propulsion_type: 'Dual-Fuel LNG',
    delivery_type: 'actual',
    status: 'completed',
  },

  // 2026 Expected Deliveries (from active orderbook)
  {
    id: 'DEL-2026-01',
    order_id: 'OB-TNK-005',
    vessel_name: 'Nordic Regent',
    vessel_class: 'Aframax',
    sector: 'tanker',
    shipyard_name: 'Samsung Heavy Industries (Geoje)',
    shipyard_country: 'South Korea',
    delivery_year: 2026,
    delivery_month: '2026-04',
    delivery_quarter: '2026-Q2',
    capacity_dwt: 115000,
    propulsion_type: 'Conventional HFO/VLSFO',
    delivery_type: 'expected',
    status: 'on_schedule',
  },
  {
    id: 'DEL-2026-02',
    order_id: 'OB-DRY-004',
    vessel_name: 'Global Frontier',
    vessel_class: 'Panamax',
    sector: 'dry',
    shipyard_name: 'Imabari Shipbuilding (Marugame & Saijo)',
    shipyard_country: 'Japan',
    delivery_year: 2026,
    delivery_month: '2026-05',
    delivery_quarter: '2026-Q2',
    capacity_dwt: 84000,
    propulsion_type: 'Methanol-Ready',
    delivery_type: 'expected',
    status: 'on_schedule',
  },
  {
    id: 'DEL-2026-03',
    order_id: 'OB-GAS-001',
    vessel_name: 'Qatar Energy Dawn',
    vessel_class: 'LNG Carrier (174k m3)',
    sector: 'gas',
    shipyard_name: 'Hanwha Ocean (Geoje Yard)',
    shipyard_country: 'South Korea',
    delivery_year: 2026,
    delivery_month: '2026-06',
    delivery_quarter: '2026-Q2',
    capacity_dwt: 95000,
    propulsion_type: 'Dual-Fuel LNG',
    delivery_type: 'expected',
    status: 'on_schedule',
  },
  {
    id: 'DEL-2026-04',
    order_id: 'OB-TNK-001',
    vessel_name: 'Frontier Titan',
    vessel_class: 'VLCC',
    sector: 'tanker',
    shipyard_name: 'HD Hyundai Heavy Industries (Ulsan)',
    shipyard_country: 'South Korea',
    delivery_year: 2026,
    delivery_month: '2026-07',
    delivery_quarter: '2026-Q3',
    capacity_dwt: 300000,
    propulsion_type: 'Dual-Fuel LNG',
    delivery_type: 'expected',
    status: 'on_schedule',
  },
  {
    id: 'DEL-2026-05',
    order_id: 'OB-DRY-001',
    vessel_name: 'Berge Hesperus',
    vessel_class: 'Capesize',
    sector: 'dry',
    shipyard_name: 'Jiangnan Shipyard (CSSC)',
    shipyard_country: 'China',
    delivery_year: 2026,
    delivery_month: '2026-08',
    delivery_quarter: '2026-Q3',
    capacity_dwt: 210000,
    propulsion_type: 'Dual-Fuel LNG',
    delivery_type: 'expected',
    status: 'on_schedule',
  },
  {
    id: 'DEL-2026-06',
    order_id: 'OB-GAS-003',
    vessel_name: 'BW Magellan Gas',
    vessel_class: 'VLGC',
    sector: 'gas',
    shipyard_name: 'HD Hyundai Heavy Industries (Ulsan)',
    shipyard_country: 'South Korea',
    delivery_year: 2026,
    delivery_month: '2026-08',
    delivery_quarter: '2026-Q3',
    capacity_dwt: 55000,
    propulsion_type: 'Dual-Fuel LNG',
    delivery_type: 'expected',
    status: 'on_schedule',
  },
  {
    id: 'DEL-2026-07',
    order_id: 'OB-CNT-001',
    vessel_name: 'Ane Maersk II',
    vessel_class: 'Ultra Large Container',
    sector: 'container',
    shipyard_name: 'HD Hyundai Heavy Industries (Ulsan)',
    shipyard_country: 'South Korea',
    delivery_year: 2026,
    delivery_month: '2026-09',
    delivery_quarter: '2026-Q3',
    capacity_dwt: 165000,
    propulsion_type: 'Methanol-Ready',
    delivery_type: 'expected',
    status: 'on_schedule',
  },
  {
    id: 'DEL-2026-08',
    order_id: 'OB-TNK-004',
    vessel_name: 'Nordic Sovereign',
    vessel_class: 'Suezmax',
    sector: 'tanker',
    shipyard_name: 'Samsung Heavy Industries (Geoje)',
    shipyard_country: 'South Korea',
    delivery_year: 2026,
    delivery_month: '2026-09',
    delivery_quarter: '2026-Q3',
    capacity_dwt: 158000,
    propulsion_type: 'Dual-Fuel LNG',
    delivery_type: 'expected',
    status: 'on_schedule',
  },
  {
    id: 'DEL-2026-09',
    order_id: 'OB-TNK-002',
    vessel_name: 'Frontier Colossus',
    vessel_class: 'VLCC',
    sector: 'tanker',
    shipyard_name: 'HD Hyundai Heavy Industries (Ulsan)',
    shipyard_country: 'South Korea',
    delivery_year: 2026,
    delivery_month: '2026-10',
    delivery_quarter: '2026-Q4',
    capacity_dwt: 300000,
    propulsion_type: 'Dual-Fuel LNG',
    delivery_type: 'expected',
    status: 'on_schedule',
  },
  {
    id: 'DEL-2026-10',
    order_id: 'OB-DRY-002',
    vessel_name: 'Berge Olympus II',
    vessel_class: 'Capesize',
    sector: 'dry',
    shipyard_name: 'Jiangnan Shipyard (CSSC)',
    shipyard_country: 'China',
    delivery_year: 2026,
    delivery_month: '2026-11',
    delivery_quarter: '2026-Q4',
    capacity_dwt: 210000,
    propulsion_type: 'Dual-Fuel LNG',
    delivery_type: 'expected',
    status: 'on_schedule',
  },

  // 2027 Deliveries
  {
    id: 'DEL-2027-01',
    order_id: 'OB-DRY-005',
    vessel_name: 'Pacific Innovator',
    vessel_class: 'Supramax',
    sector: 'dry',
    shipyard_name: 'Oshima Shipbuilding (Nagasaki)',
    shipyard_country: 'Japan',
    delivery_year: 2027,
    delivery_month: '2027-01',
    delivery_quarter: '2027-Q1',
    capacity_dwt: 64000,
    propulsion_type: 'Conventional HFO/VLSFO',
    delivery_type: 'expected',
    status: 'on_schedule',
  },
  {
    id: 'DEL-2027-02',
    order_id: 'OB-TNK-003',
    vessel_name: 'Bahri Al-Diriyah',
    vessel_class: 'VLCC',
    sector: 'tanker',
    shipyard_name: 'Dalian Shipbuilding Industry (DSIC)',
    shipyard_country: 'China',
    delivery_year: 2027,
    delivery_month: '2027-03',
    delivery_quarter: '2027-Q1',
    capacity_dwt: 318000,
    propulsion_type: 'Methanol-Ready',
    delivery_type: 'expected',
    status: 'on_schedule',
  },
  {
    id: 'DEL-2027-03',
    order_id: 'OB-DRY-003',
    vessel_name: 'Maran Pioneer',
    vessel_class: 'Capesize',
    sector: 'dry',
    shipyard_name: 'HD Hyundai Heavy Industries (Ulsan)',
    shipyard_country: 'South Korea',
    delivery_year: 2027,
    delivery_month: '2027-04',
    delivery_quarter: '2027-Q2',
    capacity_dwt: 208000,
    propulsion_type: 'Ammonia-Ready',
    delivery_type: 'expected',
    status: 'on_schedule',
  },

  // 2028 Deliveries
  {
    id: 'DEL-2028-01',
    order_id: 'OB-DRY-007',
    vessel_name: 'Mineral Antwerp',
    vessel_class: 'Capesize',
    sector: 'dry',
    shipyard_name: 'Dalian Shipbuilding Industry (DSIC)',
    shipyard_country: 'China',
    delivery_year: 2028,
    delivery_month: '2028-03',
    delivery_quarter: '2028-Q1',
    capacity_dwt: 210000,
    propulsion_type: 'Ammonia-Ready',
    delivery_type: 'expected',
    status: 'on_schedule',
  },
  {
    id: 'DEL-2028-02',
    order_id: 'OB-TNK-007',
    vessel_name: 'Aegean Harmony',
    vessel_class: 'VLCC',
    sector: 'tanker',
    shipyard_name: 'Hanwha Ocean (Geoje Yard)',
    shipyard_country: 'South Korea',
    delivery_year: 2028,
    delivery_month: '2028-06',
    delivery_quarter: '2028-Q2',
    capacity_dwt: 300000,
    propulsion_type: 'Dual-Fuel LNG',
    delivery_type: 'expected',
    status: 'on_schedule',
  },
];

export const BENCHMARK_DEMOLITIONS: DemolitionRecord[] = [
  // 2024 Actual Scrappings
  {
    id: 'DEMO-2024-01',
    vessel_name: 'Atlantic Pioneer',
    vessel_class: 'Capesize',
    sector: 'dry',
    year_built: 1999,
    demolition_year: 2024,
    demolition_month: '2024-02',
    scrapping_age_years: 25.0,
    capacity_dwt: 171000,
    scrapping_location: 'Alang (India)',
    scrap_price_per_ldt_usd: 520,
    demolition_type: 'actual',
  },
  {
    id: 'DEMO-2024-02',
    vessel_name: 'Sea Splendor',
    vessel_class: 'VLCC',
    sector: 'tanker',
    year_built: 1998,
    demolition_year: 2024,
    demolition_month: '2024-05',
    scrapping_age_years: 26.0,
    capacity_dwt: 298000,
    scrapping_location: 'Chittagong (Bangladesh)',
    scrap_price_per_ldt_usd: 545,
    demolition_type: 'actual',
  },
  {
    id: 'DEMO-2024-03',
    vessel_name: 'Ocean Express',
    vessel_class: 'Panamax',
    sector: 'dry',
    year_built: 2000,
    demolition_year: 2024,
    demolition_month: '2024-09',
    scrapping_age_years: 24.0,
    capacity_dwt: 74000,
    scrapping_location: 'Alang (India)',
    scrap_price_per_ldt_usd: 515,
    demolition_type: 'actual',
  },

  // 2025 Actual Scrappings
  {
    id: 'DEMO-2025-01',
    vessel_name: 'Cape Falcon',
    vessel_class: 'Capesize',
    sector: 'dry',
    year_built: 2000,
    demolition_year: 2025,
    demolition_month: '2025-03',
    scrapping_age_years: 25.0,
    capacity_dwt: 172500,
    scrapping_location: 'Alang (India)',
    scrap_price_per_ldt_usd: 505,
    demolition_type: 'actual',
  },
  {
    id: 'DEMO-2025-02',
    vessel_name: 'Golden Fortune',
    vessel_class: 'Aframax',
    sector: 'tanker',
    year_built: 1999,
    demolition_year: 2025,
    demolition_month: '2025-07',
    scrapping_age_years: 26.0,
    capacity_dwt: 106000,
    scrapping_location: 'Aliaga (Turkey)',
    scrap_price_per_ldt_usd: 480,
    demolition_type: 'actual',
  },
  {
    id: 'DEMO-2025-03',
    vessel_name: 'Nordic Horizon',
    vessel_class: 'Suezmax',
    sector: 'tanker',
    year_built: 2001,
    demolition_year: 2025,
    demolition_month: '2025-11',
    scrapping_age_years: 24.0,
    capacity_dwt: 153000,
    scrapping_location: 'Chittagong (Bangladesh)',
    scrap_price_per_ldt_usd: 525,
    demolition_type: 'actual',
  },

  // 2026 Projected Scrappings (Derived deterministically from vessels reaching 25+ age threshold)
  {
    id: 'DEMO-2026-01',
    vessel_name: 'Iron Transporter (Vintage)',
    vessel_class: 'Capesize',
    sector: 'dry',
    year_built: 2001,
    demolition_year: 2026,
    demolition_month: '2026-05',
    scrapping_age_years: 25.0,
    capacity_dwt: 174000,
    scrapping_location: 'Alang (India)',
    scrap_price_per_ldt_usd: 495,
    demolition_type: 'projected',
  },
  {
    id: 'DEMO-2026-02',
    vessel_name: 'Pacific Titan (Vintage)',
    vessel_class: 'VLCC',
    sector: 'tanker',
    year_built: 2000,
    demolition_year: 2026,
    demolition_month: '2026-08',
    scrapping_age_years: 26.0,
    capacity_dwt: 299000,
    scrapping_location: 'Chittagong (Bangladesh)',
    scrap_price_per_ldt_usd: 510,
    demolition_type: 'projected',
  },
  {
    id: 'DEMO-2026-03',
    vessel_name: 'Orient Harvest (Vintage)',
    vessel_class: 'Panamax',
    sector: 'dry',
    year_built: 2001,
    demolition_year: 2026,
    demolition_month: '2026-10',
    scrapping_age_years: 25.0,
    capacity_dwt: 75500,
    scrapping_location: 'Alang (India)',
    scrap_price_per_ldt_usd: 490,
    demolition_type: 'projected',
  },
  {
    id: 'DEMO-2027-01',
    vessel_name: 'Asian Glory (Vintage)',
    vessel_class: 'Capesize',
    sector: 'dry',
    year_built: 2002,
    demolition_year: 2027,
    demolition_month: '2027-04',
    scrapping_age_years: 25.0,
    capacity_dwt: 176000,
    scrapping_location: 'Alang (India)',
    scrap_price_per_ldt_usd: 485,
    demolition_type: 'projected',
  },
  {
    id: 'DEMO-2027-02',
    vessel_name: 'Gulf Majesty (Vintage)',
    vessel_class: 'VLCC',
    sector: 'tanker',
    year_built: 2001,
    demolition_year: 2027,
    demolition_month: '2027-09',
    scrapping_age_years: 26.0,
    capacity_dwt: 302000,
    scrapping_location: 'Chittagong (Bangladesh)',
    scrap_price_per_ldt_usd: 500,
    demolition_type: 'projected',
  },
];

export const BENCHMARK_FLEET_SNAPSHOTS: FleetSnapshot[] = [
  // Dry Bulk
  {
    sector: 'dry',
    vessel_class: 'Capesize',
    active_vessels_count: 1980,
    active_dwt: 378000000,
    avg_fleet_age_years: 10.4,
    orderbook_vessels_count: 182,
    orderbook_dwt: 37600000,
    orderbook_to_fleet_pct: 9.9,
  },
  {
    sector: 'dry',
    vessel_class: 'Panamax',
    active_vessels_count: 3120,
    active_dwt: 248000000,
    avg_fleet_age_years: 11.2,
    orderbook_vessels_count: 245,
    orderbook_dwt: 19800000,
    orderbook_to_fleet_pct: 8.0,
  },
  {
    sector: 'dry',
    vessel_class: 'Supramax',
    active_vessels_count: 3650,
    active_dwt: 215000000,
    avg_fleet_age_years: 11.8,
    orderbook_vessels_count: 310,
    orderbook_dwt: 19200000,
    orderbook_to_fleet_pct: 8.9,
  },
  {
    sector: 'dry',
    vessel_class: 'Handysize',
    active_vessels_count: 3200,
    active_dwt: 112000000,
    avg_fleet_age_years: 13.1,
    orderbook_vessels_count: 220,
    orderbook_dwt: 8400000,
    orderbook_to_fleet_pct: 7.5,
  },

  // Tankers
  {
    sector: 'tanker',
    vessel_class: 'VLCC',
    active_vessels_count: 910,
    active_dwt: 275000000,
    avg_fleet_age_years: 11.6,
    orderbook_vessels_count: 68,
    orderbook_dwt: 20400000,
    orderbook_to_fleet_pct: 7.4,
  },
  {
    sector: 'tanker',
    vessel_class: 'Suezmax',
    active_vessels_count: 640,
    active_dwt: 101000000,
    avg_fleet_age_years: 11.9,
    orderbook_vessels_count: 84,
    orderbook_dwt: 13200000,
    orderbook_to_fleet_pct: 13.1,
  },
  {
    sector: 'tanker',
    vessel_class: 'Aframax',
    active_vessels_count: 1120,
    active_dwt: 128000000,
    avg_fleet_age_years: 12.8,
    orderbook_vessels_count: 142,
    orderbook_dwt: 16100000,
    orderbook_to_fleet_pct: 12.6,
  },
  {
    sector: 'tanker',
    vessel_class: 'MR Tanker',
    active_vessels_count: 1840,
    active_dwt: 92000000,
    avg_fleet_age_years: 12.2,
    orderbook_vessels_count: 215,
    orderbook_dwt: 10750000,
    orderbook_to_fleet_pct: 11.7,
  },

  // Gas
  {
    sector: 'gas',
    vessel_class: 'LNG Carrier (174k m3)',
    active_vessels_count: 730,
    active_dwt: 69500000,
    avg_fleet_age_years: 8.8,
    orderbook_vessels_count: 340,
    orderbook_dwt: 32300000,
    orderbook_to_fleet_pct: 46.5,
  },
  {
    sector: 'gas',
    vessel_class: 'VLGC',
    active_vessels_count: 380,
    active_dwt: 20900000,
    avg_fleet_age_years: 9.4,
    orderbook_vessels_count: 92,
    orderbook_dwt: 5060000,
    orderbook_to_fleet_pct: 24.2,
  },

  // Container
  {
    sector: 'container',
    vessel_class: 'Ultra Large Container',
    active_vessels_count: 620,
    active_dwt: 98000000,
    avg_fleet_age_years: 8.2,
    orderbook_vessels_count: 165,
    orderbook_dwt: 26400000,
    orderbook_to_fleet_pct: 26.9,
  },
  {
    sector: 'container',
    vessel_class: 'Feeder',
    active_vessels_count: 2450,
    active_dwt: 78000000,
    avg_fleet_age_years: 13.9,
    orderbook_vessels_count: 210,
    orderbook_dwt: 6720000,
    orderbook_to_fleet_pct: 8.6,
  },
];

export const BENCHMARK_HISTORICAL_COMPARISON: HistoricalComparisonItem[] = [
  {
    period_label: 'Current (2026)',
    year: 2026,
    active_fleet_dwt: 1814400000,
    orderbook_dwt: 216330000,
    orderbook_to_fleet_pct: 11.9,
    annual_deliveries_dwt: 86400000,
    annual_demolitions_dwt: 14800000,
    avg_newbuilding_price_usd_m: 104.5,
  },
  {
    period_label: '1Y Ago (2025)',
    year: 2025,
    active_fleet_dwt: 1742800000,
    orderbook_dwt: 198500000,
    orderbook_to_fleet_pct: 11.4,
    annual_deliveries_dwt: 81200000,
    annual_demolitions_dwt: 12500000,
    avg_newbuilding_price_usd_m: 98.2,
  },
  {
    period_label: '3Y Ago (2023)',
    year: 2023,
    active_fleet_dwt: 1610000000,
    orderbook_dwt: 164200000,
    orderbook_to_fleet_pct: 10.2,
    annual_deliveries_dwt: 69500000,
    annual_demolitions_dwt: 18400000,
    avg_newbuilding_price_usd_m: 86.4,
  },
  {
    period_label: '5Y Ago (2021)',
    year: 2021,
    active_fleet_dwt: 1485000000,
    orderbook_dwt: 132100000,
    orderbook_to_fleet_pct: 8.9,
    annual_deliveries_dwt: 62400000,
    annual_demolitions_dwt: 24200000,
    avg_newbuilding_price_usd_m: 74.0,
  },
  {
    period_label: '10Y Ago (2016)',
    year: 2016,
    active_fleet_dwt: 1210000000,
    orderbook_dwt: 218000000,
    orderbook_to_fleet_pct: 18.0,
    annual_deliveries_dwt: 94500000,
    annual_demolitions_dwt: 38200000,
    avg_newbuilding_price_usd_m: 62.5,
  },
];
