/**
 * SIH 26006 Maritime Intelligence Platform
 * Module 21: Executive Emissions KPI Summary Strip
 */

import {
  TrendingDown,
  TrendingUp,
  Info,
  Flame,
  Wind,
  ShieldCheck,
  Award,
} from 'lucide-react';
import type {
  EmissionsSummaryMetrics,
} from '../../../../types/emissions';

interface EmissionsSummaryStripProps {
  summary: EmissionsSummaryMetrics;
  onSelectCiiRating?: (rating: 'A' | 'B' | 'C' | 'D' | 'E') => void;
}

// Mini pure SVG sparkline component
function MiniSparkline({ data, color }: { data: number[]; color: string }) {
  if (!data || data.length < 2) return null;
  const min = Math.min(...data);
  const max = Math.max(...data);
  const range = max - min || 1;
  const width = 80;
  const height = 24;

  const points = data
    .map((val, idx) => {
      const x = (idx / (data.length - 1)) * width;
      const y = height - ((val - min) / range) * (height - 6) - 3;
      return `${x.toFixed(1)},${y.toFixed(1)}`;
    })
    .join(' ');

  return (
    <svg width={width} height={height} style={{ overflow: 'visible' }}>
      <polyline
        fill="none"
        stroke={color}
        strokeWidth="1.75"
        strokeLinecap="round"
        strokeLinejoin="round"
        points={points}
      />
    </svg>
  );
}

export function EmissionsSummaryStrip({ summary, onSelectCiiRating }: EmissionsSummaryStripProps) {
  const ciiColors: Record<string, string> = {
    A: '#10b981',
    B: '#34d399',
    C: '#f59e0b',
    D: '#f97316',
    E: '#ef4444',
  };

  const totalCiiVessels = Object.values(summary.ciiDistribution).reduce((a, b) => a + b, 0) || 1;

  const kpis = [
    {
      id: 'co2',
      title: 'TOTAL CO₂ EMISSIONS',
      value: `${summary.totalCo2Mt.toLocaleString()}`,
      unit: 'mt',
      deltaPct: summary.co2DeltaPct,
      isReductionGood: true,
      sparkline: summary.co2Sparkline,
      sparkColor: '#10b981',
      icon: Flame,
      tooltip: 'Well-to-wake / Tank-to-wake gross metric tons of carbon dioxide generated by fuel combustion.',
    },
    {
      id: 'intensity',
      title: 'CO₂ / NAUTICAL MILE',
      value: `${summary.co2PerNauticalMileKg}`,
      unit: 'kg / nm',
      deltaPct: summary.co2PerNmDeltaPct,
      isReductionGood: true,
      sparkline: summary.intensitySparkline,
      sparkColor: '#38bdf8',
      icon: Wind,
      tooltip: 'Operational spatial carbon intensity normalized across total nautical distance sailed.',
    },
    {
      id: 'nox',
      title: 'TOTAL NOx EMISSIONS',
      value: `${summary.totalNoxMt.toLocaleString()}`,
      unit: 'mt',
      deltaPct: summary.noxDeltaPct,
      isReductionGood: true,
      sparkline: [62, 61, 63, 60, 58, 57, 56, 55, 54, 53],
      sparkColor: '#f59e0b',
      icon: Wind,
      tooltip: 'Nitrogen oxides governed under IMO Tier II & Tier III MARPOL Annex VI regulations.',
    },
    {
      id: 'sox',
      title: 'TOTAL SOx EMISSIONS',
      value: `${summary.totalSoxMt.toLocaleString()}`,
      unit: 'mt',
      deltaPct: summary.soxDeltaPct,
      isReductionGood: true,
      sparkline: [8.2, 8.0, 7.9, 7.6, 7.4, 7.2, 7.0, 6.8, 6.5, 6.2],
      sparkColor: '#a855f7',
      icon: ShieldCheck,
      tooltip: 'Sulfur oxides emitted based on bunker fuel sulfur content (0.50% global cap, 0.10% SECA zones).',
    },
    {
      id: 'eeoi',
      title: 'AVERAGE EEOI',
      value: `${summary.avgEeoi.toFixed(2)}`,
      unit: 'gCO₂ / t·nm',
      deltaPct: summary.eeoiDeltaPct,
      isReductionGood: true,
      sparkline: summary.eeoiSparkline,
      sparkColor: '#10b981',
      icon: Award,
      tooltip: 'Energy Efficiency Operational Indicator: carbon footprint per metric ton of actual cargo moved.',
    },
    {
      id: 'aer',
      title: 'AVERAGE AER',
      value: `${summary.avgAer.toFixed(2)}`,
      unit: 'gCO₂ / dwt·nm',
      deltaPct: summary.aerDeltaPct,
      isReductionGood: true,
      sparkline: summary.aerSparkline,
      sparkColor: '#0ea5e9',
      icon: Award,
      tooltip: 'Annual Efficiency Ratio: carbon emissions normalized by total vessel Deadweight Tonnage and distance.',
    },
    {
      id: 'cii',
      title: 'FLEET ATTAINED CII',
      value: `${summary.fleetCiiScore.toFixed(2)}`,
      unit: `gCO₂/dwt·nm`,
      badge: `Grade ${summary.fleetCiiRating}`,
      badgeColor: ciiColors[summary.fleetCiiRating],
      deltaPct: summary.ciiDeltaPct,
      isReductionGood: true,
      sparkline: [3.8, 3.7, 3.6, 3.6, 3.5, 3.4, 3.4, 3.3, 3.2, 3.2],
      sparkColor: ciiColors[summary.fleetCiiRating],
      icon: Award,
      tooltip: 'Fleet-wide weighted Carbon Intensity Indicator vs IMO MEPC reference baseline.',
    },
  ];

  return (
    <div
      style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
        gap: '0.875rem',
        marginBottom: '1.25rem',
      }}
    >
      {/* 7 Standard KPI Cards */}
      {kpis.map((kpi) => {
        const isFavorable = kpi.deltaPct < 0; // Negative delta in emissions is favorable
        const DeltaIcon = kpi.deltaPct <= 0 ? TrendingDown : TrendingUp;
        const deltaColor = isFavorable ? '#10b981' : '#ef4444';

        return (
          <div
            key={kpi.id}
            style={{
              background: '#0d1829',
              border: '1px solid #1e293b',
              borderRadius: '8px',
              padding: '0.875rem 1rem',
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'space-between',
              boxShadow: '0 2px 8px rgba(0, 0, 0, 0.2)',
              position: 'relative',
            }}
          >
            {/* Header: Title + Tooltip */}
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '0.35rem' }}>
              <span
                style={{
                  fontSize: '0.6875rem',
                  fontWeight: 600,
                  letterSpacing: '0.04em',
                  color: '#94a3b8',
                }}
              >
                {kpi.title}
              </span>
              <span title={kpi.tooltip} style={{ cursor: 'help', color: '#64748b' }}>
                <Info size={12} />
              </span>
            </div>

            {/* Value + Unit */}
            <div style={{ display: 'flex', alignItems: 'baseline', gap: '0.35rem', marginBottom: '0.35rem' }}>
              <span
                style={{
                  fontSize: '1.35rem',
                  fontWeight: 700,
                  fontFamily: 'var(--font-mono, monospace)',
                  color: '#f8fafc',
                }}
              >
                {kpi.value}
              </span>
              <span style={{ fontSize: '0.75rem', color: '#64748b' }}>{kpi.unit}</span>
              {kpi.badge && (
                <span
                  style={{
                    marginLeft: 'auto',
                    fontSize: '0.6875rem',
                    fontWeight: 700,
                    padding: '2px 6px',
                    borderRadius: '4px',
                    background: `${kpi.badgeColor}22`,
                    color: kpi.badgeColor,
                    border: `1px solid ${kpi.badgeColor}66`,
                  }}
                >
                  {kpi.badge}
                </span>
              )}
            </div>

            {/* Footer: Trend + Sparkline */}
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: 'auto' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '4px', fontSize: '0.6875rem', color: deltaColor, fontWeight: 600 }}>
                <DeltaIcon size={12} />
                <span>{Math.abs(kpi.deltaPct)}%</span>
                <span style={{ color: '#64748b', fontWeight: 400 }}>vs prior</span>
              </div>
              <MiniSparkline data={kpi.sparkline} color={kpi.sparkColor} />
            </div>
          </div>
        );
      })}

      {/* 8th Card: CII Rating Distribution Meter */}
      <div
        style={{
          background: '#0d1829',
          border: '1px solid #1e293b',
          borderRadius: '8px',
          padding: '0.875rem 1rem',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'space-between',
          boxShadow: '0 2px 8px rgba(0, 0, 0, 0.2)',
        }}
      >
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '0.35rem' }}>
          <span
            style={{
              fontSize: '0.6875rem',
              fontWeight: 600,
              letterSpacing: '0.04em',
              color: '#94a3b8',
            }}
          >
            CII RATING DISTRIBUTION
          </span>
          <span title="IMO MEPC A through E rating shares for active fleet." style={{ cursor: 'help', color: '#64748b' }}>
            <Info size={12} />
          </span>
        </div>

        {/* Stacked Proportional Bar */}
        <div
          style={{
            display: 'flex',
            height: '14px',
            borderRadius: '4px',
            overflow: 'hidden',
            margin: '0.5rem 0',
            background: '#1e293b',
          }}
        >
          {(['A', 'B', 'C', 'D', 'E'] as const).map((r) => {
            const count = summary.ciiDistribution[r] || 0;
            const pct = (count / totalCiiVessels) * 100;
            if (pct <= 0) return null;
            return (
              <div
                key={r}
                title={`Grade ${r}: ${count} vessels (${pct.toFixed(0)}%)`}
                style={{
                  width: `${pct}%`,
                  backgroundColor: ciiColors[r],
                  transition: 'width 0.3s ease',
                  cursor: onSelectCiiRating ? 'pointer' : 'default',
                }}
                onClick={() => onSelectCiiRating?.(r)}
              />
            );
          })}
        </div>

        {/* Legend pills */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: '0.6875rem' }}>
          {(['A', 'B', 'C', 'D', 'E'] as const).map((r) => (
            <span
              key={r}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '3px',
                color: ciiColors[r],
                fontWeight: 600,
                fontFamily: 'var(--font-mono, monospace)',
              }}
            >
              <span style={{ width: '6px', height: '6px', borderRadius: '50%', background: ciiColors[r] }} />
              {r}: {summary.ciiDistribution[r] || 0}
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}
