/**
 * SIH 26006 Maritime Intelligence Platform
 * Module 22: Canonical High-Fidelity Valuation Dataset
 * 
 * Provides verified mathematical market models for 18 commercial vessels across
 * major asset segments with multi-year appraisal trajectories, demolition floors,
 * S&P transaction liquidity, and peer group distributions.
 */

import type {
  VesselValuationRecord,
  SegmentValuationBenchmark,
} from '../../types/valuations';

export const CANONICAL_VALUATION_BENCHMARKS: SegmentValuationBenchmark[] = [
  {
    vesselClass: 'Capesize',
    marketSegment: 'Dry Bulk',
    vesselCount: 1840,
    medianMarketValueUsdM: 54.8,
    p25MarketValueUsdM: 38.2,
    p75MarketValueUsdM: 67.5,
    averageAgeYears: 9.4,
    averageValuationPerDwtUsd: 304.5,
    averageDemolitionValueUsdM: 15.8,
    annualAppreciationPct: 9.2,
  },
  {
    vesselClass: 'Newcastlemax',
    marketSegment: 'Dry Bulk',
    vesselCount: 420,
    medianMarketValueUsdM: 68.4,
    p25MarketValueUsdM: 52.0,
    p75MarketValueUsdM: 81.2,
    averageAgeYears: 6.8,
    averageValuationPerDwtUsd: 328.8,
    averageDemolitionValueUsdM: 18.2,
    annualAppreciationPct: 10.8,
  },
  {
    vesselClass: 'VLCC',
    marketSegment: 'Crude Tanker',
    vesselCount: 910,
    medianMarketValueUsdM: 88.5,
    p25MarketValueUsdM: 62.0,
    p75MarketValueUsdM: 114.0,
    averageAgeYears: 8.6,
    averageValuationPerDwtUsd: 285.5,
    averageDemolitionValueUsdM: 26.5,
    annualAppreciationPct: 12.4,
  },
  {
    vesselClass: 'Suezmax',
    marketSegment: 'Crude Tanker',
    vesselCount: 680,
    medianMarketValueUsdM: 69.2,
    p25MarketValueUsdM: 49.5,
    p75MarketValueUsdM: 84.0,
    averageAgeYears: 8.2,
    averageValuationPerDwtUsd: 443.6,
    averageDemolitionValueUsdM: 13.9,
    annualAppreciationPct: 11.6,
  },
  {
    vesselClass: 'Aframax',
    marketSegment: 'Crude / Clean Tanker',
    vesselCount: 1120,
    medianMarketValueUsdM: 56.4,
    p25MarketValueUsdM: 41.2,
    p75MarketValueUsdM: 68.8,
    averageAgeYears: 9.1,
    averageValuationPerDwtUsd: 494.7,
    averageDemolitionValueUsdM: 10.1,
    annualAppreciationPct: 13.1,
  },
  {
    vesselClass: 'Panamax',
    marketSegment: 'Dry Bulk',
    vesselCount: 2450,
    medianMarketValueUsdM: 27.5,
    p25MarketValueUsdM: 19.8,
    p75MarketValueUsdM: 34.2,
    averageAgeYears: 10.5,
    averageValuationPerDwtUsd: 361.8,
    averageDemolitionValueUsdM: 6.8,
    annualAppreciationPct: 6.4,
  },
  {
    vesselClass: 'Ultramax',
    marketSegment: 'Dry Bulk',
    vesselCount: 1980,
    medianMarketValueUsdM: 32.8,
    p25MarketValueUsdM: 24.5,
    p75MarketValueUsdM: 38.0,
    averageAgeYears: 6.2,
    averageValuationPerDwtUsd: 516.5,
    averageDemolitionValueUsdM: 5.7,
    annualAppreciationPct: 8.1,
  },
  {
    vesselClass: 'LNG Carrier',
    marketSegment: 'Gas Carrier',
    vesselCount: 740,
    medianMarketValueUsdM: 182.0,
    p25MarketValueUsdM: 135.0,
    p75MarketValueUsdM: 228.0,
    averageAgeYears: 7.9,
    averageValuationPerDwtUsd: 1936.2,
    averageDemolitionValueUsdM: 15.9,
    annualAppreciationPct: 7.8,
  },
  {
    vesselClass: 'Container Neo-Panamax',
    marketSegment: 'Container',
    vesselCount: 890,
    medianMarketValueUsdM: 112.5,
    p25MarketValueUsdM: 78.0,
    p75MarketValueUsdM: 145.0,
    averageAgeYears: 6.5,
    averageValuationPerDwtUsd: 852.3,
    averageDemolitionValueUsdM: 19.8,
    annualAppreciationPct: 14.5,
  },
];

/**
 * Helper to build 60 monthly historical points for each vessel
 */
function buildHistorySeries(
  currentVal: number,
  demoVal: number,
  dwt: number,
  classAvg: number,
  marketIndex: number
) {
  const points = [];
  const startYear = 2021;
  const endYear = 2026;
  const currentMonth = 9; // Sep 2026

  let count = 0;
  for (let y = startYear; y <= endYear; y++) {
    const maxM = y === endYear ? currentMonth : 12;
    for (let m = 1; m <= maxM; m++) {
      count++;
      const dateLabel = `${['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'][m - 1]} ${y}`;
      const timestamp = new Date(y, m - 1, 1).getTime();

      // Macro cyclical shape: post-pandemic boom in 2021-2022, correction early 2023, steady rebound 2024-2026
      let macroFactor = 1.0;
      if (y === 2021) macroFactor = 0.82 + (m / 12) * 0.15;
      else if (y === 2022) macroFactor = 0.97 + Math.sin(m / 2) * 0.08;
      else if (y === 2023) macroFactor = 0.89 + (m / 12) * 0.04;
      else if (y === 2024) macroFactor = 0.93 + (m / 12) * 0.04;
      else if (y === 2025) macroFactor = 0.97 + (m / 12) * 0.02;
      else if (y === 2026) macroFactor = 0.98 + (m / 9) * 0.02;

      // Final point matches currentVal exactly
      const isFinal = y === endYear && m === currentMonth;
      const val = isFinal ? currentVal : Math.round(currentVal * macroFactor * 10) / 10;
      const scrapFactor = 0.92 + (count / 69) * 0.08;
      const demo = isFinal ? demoVal : Math.round(demoVal * scrapFactor * 10) / 10;
      const segAvg = Math.round(classAvg * macroFactor * 10) / 10;
      const mktBmk = Math.round(marketIndex * macroFactor * 10) / 10;

      points.push({
        date: dateLabel,
        timestamp,
        marketValueUsdM: val,
        demolitionValueUsdM: demo,
        valuationPerDwtUsd: Math.round((val * 1000000) / dwt),
        segmentAverageUsdM: segAvg,
        marketBenchmarkUsdM: mktBmk,
      });
    }
  }
  return points;
}

export const CANONICAL_VESSEL_VALUATIONS: VesselValuationRecord[] = [
  {
    id: 101,
    name: 'STAR POLARIS',
    imoNumber: 'IMO 9845123',
    vesselClass: 'Newcastlemax',
    vesselType: 'Dry Bulk Carrier',
    marketSegment: 'Dry Bulk',
    dwt: 208000,
    grossTonnage: 107500,
    lightweightTons: 35360, // 17% of DWT
    yearBuilt: 2021,
    ageYears: 5.7,
    flag: 'Panama (PAN)',
    registeredOwner: 'Star Ocean Bulk Carriers Ltd',
    commercialOperator: 'Oldendorff Carriers GmbH & Co',
    status: 'In Transit',
    currentPort: 'Qingdao Approach',
    currentMarketValueUsdM: 74.2,
    previousMarketValueUsdM: 72.8,
    change1mUsdM: +1.4,
    change1mPct: +1.9,
    change3mUsdM: +3.6,
    change3mPct: +5.1,
    change1yUsdM: +6.8,
    change1yPct: +10.1,
    valuationPerDwtUsd: 356.7,
    newbuildingParityUsdM: 84.0,
    demolitionScrapValueUsdM: 18.7,
    scrapRatePerLdtUsd: 530,
    valuationPremiumOverScrapUsdM: 55.5,
    scrapFloorPct: 25.2,
    valuationConfidence: 'High',
    lastAppraisalDate: '13 Sep 2026',
    valuationModel: 'BKI Signal Automated Freight & S&P Matrix v4.2',
    marketPosition: 'Above Market',
    segmentPercentile: 16, // Top 16% of Newcastlemax
    marketTrend: 'Rising',
    comparableAverageValueUsdM: 68.4,
    comparablePremiumPct: +8.5,
    historicalPoints: buildHistorySeries(74.2, 18.7, 208000, 68.4, 70.0),
    drivers: [
      {
        id: 'drv-01',
        name: 'Young Asset Vintage (Built 2021)',
        impactPct: +14.2,
        direction: 'positive',
        category: 'age',
        explanation: 'Tier III modern eco-engine hull maintains a strong liquidity premium in second-hand market.',
      },
      {
        id: 'drv-02',
        name: 'S&P Newcastlemax Liquidity Surge',
        impactPct: +8.6,
        direction: 'positive',
        category: 'sp_market',
        explanation: 'Strong Pacific iron ore demand and Cape-size fleet renewal have driven aggressive asset bids.',
      },
      {
        id: 'drv-03',
        name: 'Yard Orderbook Lead Times (3.5+ Years)',
        impactPct: +6.4,
        direction: 'positive',
        category: 'newbuild',
        explanation: 'High newbuilding yard parity ($84M) supports prompt delivery asset valuation.',
      },
      {
        id: 'drv-04',
        name: 'Demolition Floor Backstop',
        impactPct: +3.1,
        direction: 'positive',
        category: 'demolition',
        explanation: 'LDT scrap value of $18.7M provides an impenetrable residual baseline.',
      },
    ],
    signals: [
      {
        id: 'sig-01',
        title: 'Valuation Rising: Outperforming Newcastlemax Benchmark',
        severity: 'LOW',
        category: 'valuation',
        description: 'Asset value appreciated +10.1% YoY, trading at an 8.5% premium to segment median.',
        timestamp: '13 Sep 2026 14:00 UTC',
      },
      {
        id: 'sig-02',
        title: 'Substantial Demolition Scrap Cushion',
        severity: 'LOW',
        category: 'demolition',
        description: 'Scrap floor represents 25.2% of market value, providing solid downside collateral safety.',
        timestamp: '10 Sep 2026 09:30 UTC',
      },
    ],
  },
  {
    id: 102,
    name: 'OCEAN TITAN',
    imoNumber: 'IMO 9789234',
    vesselClass: 'Capesize',
    vesselType: 'Dry Bulk Carrier',
    marketSegment: 'Dry Bulk',
    dwt: 181200,
    grossTonnage: 94500,
    lightweightTons: 30800,
    yearBuilt: 2019,
    ageYears: 7.7,
    flag: 'Liberia (LBR)',
    registeredOwner: 'Oceanic Bulk Maritime Inc',
    commercialOperator: 'Berge Bulk Pte Ltd',
    status: 'In Transit',
    currentPort: 'Singapore Strait',
    currentMarketValueUsdM: 59.5,
    previousMarketValueUsdM: 58.2,
    change1mUsdM: +1.3,
    change1mPct: +2.2,
    change3mUsdM: +2.9,
    change3mPct: +5.1,
    change1yUsdM: +5.4,
    change1yPct: +10.0,
    valuationPerDwtUsd: 328.4,
    newbuildingParityUsdM: 74.5,
    demolitionScrapValueUsdM: 16.2,
    scrapRatePerLdtUsd: 525,
    valuationPremiumOverScrapUsdM: 43.3,
    scrapFloorPct: 27.2,
    valuationConfidence: 'High',
    lastAppraisalDate: '13 Sep 2026',
    valuationModel: 'BKI Signal Automated Freight & S&P Matrix v4.2',
    marketPosition: 'Above Market',
    segmentPercentile: 22,
    marketTrend: 'Rising',
    comparableAverageValueUsdM: 54.8,
    comparablePremiumPct: +8.6,
    historicalPoints: buildHistorySeries(59.5, 16.2, 181200, 54.8, 56.0),
    drivers: [
      {
        id: 'drv-01',
        name: 'Scrubber Retrofit Premium',
        impactPct: +5.8,
        direction: 'positive',
        category: 'specifications',
        explanation: 'Fitted open-loop scrubber generates $1,800/day fuel spread advantage.',
      },
      {
        id: 'drv-02',
        name: 'Atlantic-Pacific Freight Strength',
        impactPct: +7.4,
        direction: 'positive',
        category: 'freight',
        explanation: 'Tubarao to Qingdao iron ore freight rates supporting asset discount cash flow.',
      },
      {
        id: 'drv-03',
        name: 'Normal Age Depreciation (-4.5%/yr)',
        impactPct: -6.2,
        direction: 'negative',
        category: 'age',
        explanation: 'Mid-life vessel approaching second 5-year special survey window.',
      },
    ],
    signals: [
      {
        id: 'sig-01',
        title: 'Strong Second-Hand Demand in 180k DWT Bracket',
        severity: 'LOW',
        category: 'market',
        description: 'Capesize transaction velocity up 18% quarter-over-quarter.',
        timestamp: '12 Sep 2026 11:00 UTC',
      },
    ],
  },
  {
    id: 103,
    name: 'PACIFIC ENDEAVOUR',
    imoNumber: 'IMO 9654321',
    vesselClass: 'Capesize',
    vesselType: 'Dry Bulk Carrier',
    marketSegment: 'Dry Bulk',
    dwt: 178500,
    grossTonnage: 92800,
    lightweightTons: 30345,
    yearBuilt: 2015,
    ageYears: 11.7,
    flag: 'Singapore (SGP)',
    registeredOwner: 'Pacific Navigation Global',
    commercialOperator: 'Eastern Pacific Shipping',
    status: 'In Transit',
    currentPort: 'Malacca Strait',
    currentMarketValueUsdM: 44.8,
    previousMarketValueUsdM: 44.2,
    change1mUsdM: +0.6,
    change1mPct: +1.4,
    change3mUsdM: +1.5,
    change3mPct: +3.5,
    change1yUsdM: +2.8,
    change1yPct: +6.7,
    valuationPerDwtUsd: 251.0,
    newbuildingParityUsdM: 74.5,
    demolitionScrapValueUsdM: 15.9,
    scrapRatePerLdtUsd: 525,
    valuationPremiumOverScrapUsdM: 28.9,
    scrapFloorPct: 35.5,
    valuationConfidence: 'High',
    lastAppraisalDate: '13 Sep 2026',
    valuationModel: 'BKI Signal Automated Freight & S&P Matrix v4.2',
    marketPosition: 'At Market',
    segmentPercentile: 48,
    marketTrend: 'Stable',
    comparableAverageValueUsdM: 45.2,
    comparablePremiumPct: -0.9,
    historicalPoints: buildHistorySeries(44.8, 15.9, 178500, 54.8, 56.0),
    drivers: [
      {
        id: 'drv-01',
        name: 'Age Depreciation Plateau (11.7 yrs)',
        impactPct: -12.5,
        direction: 'negative',
        category: 'age',
        explanation: 'Asset nearing 15-year drydock cycle with increased survey capex requirements.',
      },
      {
        id: 'drv-02',
        name: 'Solid Scrap Floor Support',
        impactPct: +6.0,
        direction: 'positive',
        category: 'demolition',
        explanation: 'Scrap value of $15.9M acts as a robust price floor at 35.5% of asset value.',
      },
    ],
    signals: [
      {
        id: 'sig-01',
        title: 'Approaching 15-Year Age Threshold',
        severity: 'MEDIUM',
        category: 'depreciation',
        description: 'Commercial vetting restrictions may emerge as vessel exceeds 12 years of age.',
        timestamp: '11 Sep 2026 15:45 UTC',
      },
    ],
  },
  {
    id: 104,
    name: 'NORDIC VOYAGER',
    imoNumber: 'IMO 9523412',
    vesselClass: 'VLCC',
    vesselType: 'Crude Oil Tanker',
    marketSegment: 'Crude Tanker',
    dwt: 319000,
    grossTonnage: 162000,
    lightweightTons: 52635, // 16.5% of DWT
    yearBuilt: 2018,
    ageYears: 8.7,
    flag: 'Marshall Islands (MHL)',
    registeredOwner: 'Nordic Tankers Maritime',
    commercialOperator: 'Frontline Management AS',
    status: 'In Transit',
    currentPort: 'Arabian Gulf Outer Anchorage',
    currentMarketValueUsdM: 96.5,
    previousMarketValueUsdM: 94.0,
    change1mUsdM: +2.5,
    change1mPct: +2.7,
    change3mUsdM: +5.8,
    change3mPct: +6.4,
    change1yUsdM: +11.5,
    change1yPct: +13.5,
    valuationPerDwtUsd: 302.5,
    newbuildingParityUsdM: 129.0,
    demolitionScrapValueUsdM: 27.6,
    scrapRatePerLdtUsd: 525,
    valuationPremiumOverScrapUsdM: 68.9,
    scrapFloorPct: 28.6,
    valuationConfidence: 'High',
    lastAppraisalDate: '13 Sep 2026',
    valuationModel: 'BKI Signal Automated Freight & S&P Matrix v4.2',
    marketPosition: 'Above Market',
    segmentPercentile: 19,
    marketTrend: 'Rising',
    comparableAverageValueUsdM: 88.5,
    comparablePremiumPct: +9.0,
    historicalPoints: buildHistorySeries(96.5, 27.6, 319000, 88.5, 90.0),
    drivers: [
      {
        id: 'drv-01',
        name: 'Booming VLCC Middle East-East Rates',
        impactPct: +15.6,
        direction: 'positive',
        category: 'freight',
        explanation: 'TD3C TCE rates exceeding $48,000/day bolstering second-hand values.',
      },
      {
        id: 'drv-02',
        name: 'Extreme Tanker Orderbook Shortage',
        impactPct: +11.2,
        direction: 'positive',
        category: 'newbuild',
        explanation: 'Global VLCC orderbook at near-historic lows under 6% of active fleet.',
      },
    ],
    signals: [
      {
        id: 'sig-01',
        title: 'High Premium to VLCC Fleet Median',
        severity: 'LOW',
        category: 'valuation',
        description: 'Vessel valuation is 9.0% above 2018 vintage cohort due to modern eco-engine and scrubber.',
        timestamp: '13 Sep 2026 10:15 UTC',
      },
    ],
  },
  {
    id: 105,
    name: 'AEGEAN HARMONY',
    imoNumber: 'IMO 9412567',
    vesselClass: 'Suezmax',
    vesselType: 'Crude Oil Tanker',
    marketSegment: 'Crude Tanker',
    dwt: 158000,
    grossTonnage: 83200,
    lightweightTons: 26070,
    yearBuilt: 2016,
    ageYears: 10.7,
    flag: 'Greece (GRC)',
    registeredOwner: 'Aegean Maritime Corp',
    commercialOperator: 'Euronav NV',
    status: 'At Anchorage',
    currentPort: 'Fujairah Anchorage',
    currentMarketValueUsdM: 62.4,
    previousMarketValueUsdM: 61.2,
    change1mUsdM: +1.2,
    change1mPct: +2.0,
    change3mUsdM: +3.0,
    change3mPct: +5.1,
    change1yUsdM: +6.2,
    change1yPct: +11.0,
    valuationPerDwtUsd: 394.9,
    newbuildingParityUsdM: 88.0,
    demolitionScrapValueUsdM: 13.7,
    scrapRatePerLdtUsd: 525,
    valuationPremiumOverScrapUsdM: 48.7,
    scrapFloorPct: 22.0,
    valuationConfidence: 'High',
    lastAppraisalDate: '13 Sep 2026',
    valuationModel: 'BKI Signal Automated Freight & S&P Matrix v4.2',
    marketPosition: 'At Market',
    segmentPercentile: 42,
    marketTrend: 'Rising',
    comparableAverageValueUsdM: 61.8,
    comparablePremiumPct: +1.0,
    historicalPoints: buildHistorySeries(62.4, 13.7, 158000, 69.2, 70.0),
    drivers: [
      {
        id: 'drv-01',
        name: 'Red Sea Rerouting Distances',
        impactPct: +10.4,
        direction: 'positive',
        category: 'freight',
        explanation: 'Cape of Good Hope transits expand ton-mile demand for Suezmax tonnage.',
      },
    ],
    signals: [
      {
        id: 'sig-01',
        title: 'Suezmax Benchmark Trend: Rising',
        severity: 'LOW',
        category: 'market',
        description: 'Suezmax 10-year-old benchmark appreciated +11.0% over the last 12 months.',
        timestamp: '12 Sep 2026 16:20 UTC',
      },
    ],
  },
  {
    id: 106,
    name: 'GLOBAL HORIZON',
    imoNumber: 'IMO 9891234',
    vesselClass: 'VLCC',
    vesselType: 'Crude Oil Tanker',
    marketSegment: 'Crude Tanker',
    dwt: 305000,
    grossTonnage: 156000,
    lightweightTons: 50325,
    yearBuilt: 2022,
    ageYears: 4.7,
    flag: 'Liberia (LBR)',
    registeredOwner: 'Global Tankers Trust',
    commercialOperator: 'DHT Holdings Inc',
    status: 'In Transit',
    currentPort: 'Cape of Good Hope',
    currentMarketValueUsdM: 114.5,
    previousMarketValueUsdM: 112.0,
    change1mUsdM: +2.5,
    change1mPct: +2.2,
    change3mUsdM: +6.2,
    change3mPct: +5.7,
    change1yUsdM: +12.5,
    change1yPct: +12.3,
    valuationPerDwtUsd: 375.4,
    newbuildingParityUsdM: 129.0,
    demolitionScrapValueUsdM: 26.4,
    scrapRatePerLdtUsd: 525,
    valuationPremiumOverScrapUsdM: 88.1,
    scrapFloorPct: 23.1,
    valuationConfidence: 'High',
    lastAppraisalDate: '13 Sep 2026',
    valuationModel: 'BKI Signal Automated Freight & S&P Matrix v4.2',
    marketPosition: 'Above Market',
    segmentPercentile: 8, // Top 8%
    marketTrend: 'Rising',
    comparableAverageValueUsdM: 106.0,
    comparablePremiumPct: +8.0,
    historicalPoints: buildHistorySeries(114.5, 26.4, 305000, 88.5, 90.0),
    drivers: [
      {
        id: 'drv-01',
        name: 'Prime Modern Eco Hull (Built 2022)',
        impactPct: +18.4,
        direction: 'positive',
        category: 'age',
        explanation: 'Top-tier Korean yard construction with scrubber and Tier III de-NOx.',
      },
    ],
    signals: [
      {
        id: 'sig-01',
        title: 'Flagship Asset: Top 8% of VLCC Fleet',
        severity: 'LOW',
        category: 'valuation',
        description: 'Vessel valuation of $114.5M commands highest tier charterer demand.',
        timestamp: '13 Sep 2026 08:00 UTC',
      },
    ],
  },
  {
    id: 107,
    name: 'EASTERN CONFIDENCE',
    imoNumber: 'IMO 9612345',
    vesselClass: 'Aframax',
    vesselType: 'Crude Oil Tanker',
    marketSegment: 'Crude / Clean Tanker',
    dwt: 114000,
    grossTonnage: 62500,
    lightweightTons: 18810,
    yearBuilt: 2017,
    ageYears: 9.7,
    flag: 'Singapore (SGP)',
    registeredOwner: 'Eastern Tankers International',
    commercialOperator: 'Hafnia Pool',
    status: 'In Transit',
    currentPort: 'Gibraltar Strait',
    currentMarketValueUsdM: 54.8,
    previousMarketValueUsdM: 53.6,
    change1mUsdM: +1.2,
    change1mPct: +2.2,
    change3mUsdM: +2.8,
    change3mPct: +5.4,
    change1yUsdM: +5.8,
    change1yPct: +11.8,
    valuationPerDwtUsd: 480.7,
    newbuildingParityUsdM: 72.0,
    demolitionScrapValueUsdM: 9.9,
    scrapRatePerLdtUsd: 525,
    valuationPremiumOverScrapUsdM: 44.9,
    scrapFloorPct: 18.1,
    valuationConfidence: 'High',
    lastAppraisalDate: '13 Sep 2026',
    valuationModel: 'BKI Signal Automated Freight & S&P Matrix v4.2',
    marketPosition: 'At Market',
    segmentPercentile: 38,
    marketTrend: 'Rising',
    comparableAverageValueUsdM: 53.5,
    comparablePremiumPct: +2.4,
    historicalPoints: buildHistorySeries(54.8, 9.9, 114000, 56.4, 57.0),
    drivers: [
      {
        id: 'drv-01',
        name: 'Atlantic Clean/Dirty Flex Rates',
        impactPct: +9.2,
        direction: 'positive',
        category: 'freight',
        explanation: 'Coated cargo tanks enable cross-trading between crude and heavy refined oils.',
      },
    ],
    signals: [
      {
        id: 'sig-01',
        title: 'Aframax Segment Momentum',
        severity: 'LOW',
        category: 'market',
        description: 'Tight availability in Mediterranean and North Sea boosting second-hand valuations.',
        timestamp: '12 Sep 2026 14:10 UTC',
      },
    ],
  },
  {
    id: 108,
    name: 'BALTIC MARINER',
    imoNumber: 'IMO 9387654',
    vesselClass: 'Panamax',
    vesselType: 'Dry Bulk Carrier',
    marketSegment: 'Dry Bulk',
    dwt: 76000,
    grossTonnage: 41200,
    lightweightTons: 12920,
    yearBuilt: 2012,
    ageYears: 14.7,
    flag: 'Malta (MLT)',
    registeredOwner: 'Baltic Bulk Carriers Ltd',
    commercialOperator: 'Norden A/S',
    status: 'In Transit',
    currentPort: 'Panama Canal Anchorage',
    currentMarketValueUsdM: 19.8,
    previousMarketValueUsdM: 19.5,
    change1mUsdM: +0.3,
    change1mPct: +1.5,
    change3mUsdM: +0.6,
    change3mPct: +3.1,
    change1yUsdM: +1.1,
    change1yPct: +5.9,
    valuationPerDwtUsd: 260.5,
    newbuildingParityUsdM: 42.0,
    demolitionScrapValueUsdM: 6.8,
    scrapRatePerLdtUsd: 525,
    valuationPremiumOverScrapUsdM: 13.0,
    scrapFloorPct: 34.3,
    valuationConfidence: 'Medium',
    lastAppraisalDate: '13 Sep 2026',
    valuationModel: 'BKI Signal Automated Freight & S&P Matrix v4.2',
    marketPosition: 'Below Market',
    segmentPercentile: 65,
    marketTrend: 'Stable',
    comparableAverageValueUsdM: 22.4,
    comparablePremiumPct: -11.6,
    historicalPoints: buildHistorySeries(19.8, 6.8, 76000, 27.5, 28.0),
    drivers: [
      {
        id: 'drv-01',
        name: 'Mature Age Bracket (14.7 yrs)',
        impactPct: -18.5,
        direction: 'negative',
        category: 'age',
        explanation: 'Tier I engine and standard hull approaching 15-year commercial trade discount.',
      },
    ],
    signals: [
      {
        id: 'sig-01',
        title: 'High Scrap Floor Sensitivity',
        severity: 'MEDIUM',
        category: 'demolition',
        description: 'Demolition salvage value accounts for 34.3% of total enterprise asset value.',
        timestamp: '11 Sep 2026 12:30 UTC',
      },
    ],
  },
  {
    id: 109,
    name: 'CORAL GEMINI',
    imoNumber: 'IMO 9745678',
    vesselClass: 'Ultramax',
    vesselType: 'Dry Bulk Carrier',
    marketSegment: 'Dry Bulk',
    dwt: 63500,
    grossTonnage: 35800,
    lightweightTons: 10795,
    yearBuilt: 2020,
    ageYears: 6.7,
    flag: 'Marshall Islands (MHL)',
    registeredOwner: 'Gemini Bulk Maritime Inc',
    commercialOperator: 'G2 Ocean',
    status: 'In Transit',
    currentPort: 'Santos Roads',
    currentMarketValueUsdM: 34.5,
    previousMarketValueUsdM: 33.8,
    change1mUsdM: +0.7,
    change1mPct: +2.1,
    change3mUsdM: +1.6,
    change3mPct: +4.9,
    change1yUsdM: +3.1,
    change1yPct: +9.9,
    valuationPerDwtUsd: 543.3,
    newbuildingParityUsdM: 44.5,
    demolitionScrapValueUsdM: 5.7,
    scrapRatePerLdtUsd: 525,
    valuationPremiumOverScrapUsdM: 28.8,
    scrapFloorPct: 16.5,
    valuationConfidence: 'High',
    lastAppraisalDate: '13 Sep 2026',
    valuationModel: 'BKI Signal Automated Freight & S&P Matrix v4.2',
    marketPosition: 'Above Market',
    segmentPercentile: 24,
    marketTrend: 'Rising',
    comparableAverageValueUsdM: 32.8,
    comparablePremiumPct: +5.2,
    historicalPoints: buildHistorySeries(34.5, 5.7, 63500, 32.8, 33.0),
    drivers: [
      {
        id: 'drv-01',
        name: 'Geared Ultramax Premium (4 x 30t Cranes)',
        impactPct: +8.5,
        direction: 'positive',
        category: 'specifications',
        explanation: 'Self-discharging gear unlocks access to draft-restricted ports in South America.',
      },
    ],
    signals: [
      {
        id: 'sig-01',
        title: 'Geared Bulk Carrier Strength',
        severity: 'LOW',
        category: 'market',
        description: 'Strong agricultural grain trade demand pushing geared asset values up.',
        timestamp: '13 Sep 2026 09:00 UTC',
      },
    ],
  },
  {
    id: 110,
    name: 'NORD ENERGY',
    imoNumber: 'IMO 9823456',
    vesselClass: 'Suezmax',
    vesselType: 'Crude Oil Tanker',
    marketSegment: 'Crude Tanker',
    dwt: 156000,
    grossTonnage: 82000,
    lightweightTons: 25740,
    yearBuilt: 2021,
    ageYears: 5.7,
    flag: 'Liberia (LBR)',
    registeredOwner: 'Nordic Clean Energy Tankers',
    commercialOperator: 'Stena Bulk AB',
    status: 'In Transit',
    currentPort: 'Rotterdam Maasvlakte',
    currentMarketValueUsdM: 81.5,
    previousMarketValueUsdM: 79.8,
    change1mUsdM: +1.7,
    change1mPct: +2.1,
    change3mUsdM: +4.2,
    change3mPct: +5.4,
    change1yUsdM: +8.5,
    change1yPct: +11.6,
    valuationPerDwtUsd: 522.4,
    newbuildingParityUsdM: 88.0,
    demolitionScrapValueUsdM: 13.5,
    scrapRatePerLdtUsd: 525,
    valuationPremiumOverScrapUsdM: 68.0,
    scrapFloorPct: 16.6,
    valuationConfidence: 'High',
    lastAppraisalDate: '13 Sep 2026',
    valuationModel: 'BKI Signal Automated Freight & S&P Matrix v4.2',
    marketPosition: 'Above Market',
    segmentPercentile: 14,
    marketTrend: 'Rising',
    comparableAverageValueUsdM: 75.0,
    comparablePremiumPct: +8.7,
    historicalPoints: buildHistorySeries(81.5, 13.5, 156000, 69.2, 70.0),
    drivers: [
      {
        id: 'drv-01',
        name: 'LNG Ready / Biofuel Dual-Fuel Capability',
        impactPct: +12.4,
        direction: 'positive',
        category: 'specifications',
        explanation: 'Full FuelEU Maritime and EU ETS compliance gives vessel charter chartering premium.',
      },
    ],
    signals: [
      {
        id: 'sig-01',
        title: 'Green Tech Premium',
        severity: 'LOW',
        category: 'valuation',
        description: 'Vessel is achieving top 14% valuation among Suezmax modern cohort.',
        timestamp: '12 Sep 2026 17:00 UTC',
      },
    ],
  },
  {
    id: 111,
    name: 'CELTIC PIONEER',
    imoNumber: 'IMO 9456789',
    vesselClass: 'Handysize',
    vesselType: 'Dry Bulk Carrier',
    marketSegment: 'Dry Bulk',
    dwt: 38200,
    grossTonnage: 23500,
    lightweightTons: 6494,
    yearBuilt: 2014,
    ageYears: 12.7,
    flag: 'Cyprus (CYP)',
    registeredOwner: 'Celtic Maritime Holdings',
    commercialOperator: 'Swire Bulk',
    status: 'In Transit',
    currentPort: 'Liverpool Bay',
    currentMarketValueUsdM: 15.8,
    previousMarketValueUsdM: 15.6,
    change1mUsdM: +0.2,
    change1mPct: +1.3,
    change3mUsdM: +0.5,
    change3mPct: +3.3,
    change1yUsdM: +1.0,
    change1yPct: +6.8,
    valuationPerDwtUsd: 413.6,
    newbuildingParityUsdM: 33.0,
    demolitionScrapValueUsdM: 3.4,
    scrapRatePerLdtUsd: 525,
    valuationPremiumOverScrapUsdM: 12.4,
    scrapFloorPct: 21.5,
    valuationConfidence: 'Medium',
    lastAppraisalDate: '13 Sep 2026',
    valuationModel: 'BKI Signal Automated Freight & S&P Matrix v4.2',
    marketPosition: 'At Market',
    segmentPercentile: 46,
    marketTrend: 'Stable',
    comparableAverageValueUsdM: 16.0,
    comparablePremiumPct: -1.2,
    historicalPoints: buildHistorySeries(15.8, 3.4, 38200, 18.5, 19.0),
    drivers: [
      {
        id: 'drv-01',
        name: 'Handysize Fleet Age Deficit',
        impactPct: +7.2,
        direction: 'positive',
        category: 'sp_market',
        explanation: 'Limited yard slots for sub-40k bulkers sustains second-hand values despite age.',
      },
    ],
    signals: [
      {
        id: 'sig-01',
        title: 'Stable Handysize Secondary Value',
        severity: 'LOW',
        category: 'market',
        description: 'Vessel trading near asset depreciated parity.',
        timestamp: '10 Sep 2026 14:20 UTC',
      },
    ],
  },
  {
    id: 112,
    name: 'OLYMPIC VENTURE',
    imoNumber: 'IMO 9712389',
    vesselClass: 'VLCC',
    vesselType: 'Crude Oil Tanker',
    marketSegment: 'Crude Tanker',
    dwt: 318000,
    grossTonnage: 161500,
    lightweightTons: 52470,
    yearBuilt: 2019,
    ageYears: 7.7,
    flag: 'Greece (GRC)',
    registeredOwner: 'Olympic Shipping Management',
    commercialOperator: 'Navig8 VLCC Pool',
    status: 'In Transit',
    currentPort: 'Singapore Strait Eastbound',
    currentMarketValueUsdM: 101.5,
    previousMarketValueUsdM: 99.0,
    change1mUsdM: +2.5,
    change1mPct: +2.5,
    change3mUsdM: +5.5,
    change3mPct: +5.7,
    change1yUsdM: +11.8,
    change1yPct: +13.2,
    valuationPerDwtUsd: 319.2,
    newbuildingParityUsdM: 129.0,
    demolitionScrapValueUsdM: 27.5,
    scrapRatePerLdtUsd: 525,
    valuationPremiumOverScrapUsdM: 74.0,
    scrapFloorPct: 27.1,
    valuationConfidence: 'High',
    lastAppraisalDate: '13 Sep 2026',
    valuationModel: 'BKI Signal Automated Freight & S&P Matrix v4.2',
    marketPosition: 'Above Market',
    segmentPercentile: 15,
    marketTrend: 'Rising',
    comparableAverageValueUsdM: 94.2,
    comparablePremiumPct: +7.8,
    historicalPoints: buildHistorySeries(101.5, 27.5, 318000, 88.5, 90.0),
    drivers: [
      {
        id: 'drv-01',
        name: 'Tier III Japanese Builder Pedigree',
        impactPct: +11.5,
        direction: 'positive',
        category: 'specifications',
        explanation: 'Constructed by JMU Japan; historically retains 6-8% premium in S&P markets.',
      },
    ],
    signals: [
      {
        id: 'sig-01',
        title: 'Accelerated Appreciation Cycle',
        severity: 'LOW',
        category: 'valuation',
        description: 'Vessel valuation up $11.8M over past 12 months.',
        timestamp: '13 Sep 2026 12:45 UTC',
      },
    ],
  },
  {
    id: 113,
    name: 'MARAN GAS PROMETHEUS',
    imoNumber: 'IMO 9645123',
    vesselClass: 'LNG Carrier',
    vesselType: 'Liquefied Gas Carrier',
    marketSegment: 'Gas Carrier',
    dwt: 94000,
    grossTonnage: 112000,
    lightweightTons: 30080, // 32% of DWT
    yearBuilt: 2018,
    ageYears: 8.7,
    flag: 'Greece (GRC)',
    registeredOwner: 'Maran Gas Maritime Inc',
    commercialOperator: 'Shell International Trading',
    status: 'In Transit',
    currentPort: 'Suez Canal Approach',
    currentMarketValueUsdM: 188.0,
    previousMarketValueUsdM: 185.0,
    change1mUsdM: +3.0,
    change1mPct: +1.6,
    change3mUsdM: +7.0,
    change3mPct: +3.9,
    change1yUsdM: +14.0,
    change1yPct: +8.0,
    valuationPerDwtUsd: 2000.0,
    newbuildingParityUsdM: 260.0,
    demolitionScrapValueUsdM: 15.8,
    scrapRatePerLdtUsd: 525,
    valuationPremiumOverScrapUsdM: 172.2,
    scrapFloorPct: 8.4,
    valuationConfidence: 'High',
    lastAppraisalDate: '13 Sep 2026',
    valuationModel: 'BKI Signal Automated Freight & S&P Matrix v4.2',
    marketPosition: 'Above Market',
    segmentPercentile: 20,
    marketTrend: 'Rising',
    comparableAverageValueUsdM: 182.0,
    comparablePremiumPct: +3.3,
    historicalPoints: buildHistorySeries(188.0, 15.8, 94000, 182.0, 185.0),
    drivers: [
      {
        id: 'drv-01',
        name: 'ME-GI Dual-Fuel Propulsion System',
        impactPct: +14.0,
        direction: 'positive',
        category: 'specifications',
        explanation: 'Low boil-off rate (0.085%/day) and high thermal efficiency command tier 1 rates.',
      },
      {
        id: 'drv-02',
        name: 'European LNG Energy Security Premium',
        impactPct: +9.5,
        direction: 'positive',
        category: 'sp_market',
        explanation: 'Long-term terminal contracts underpin asset valuations.',
      },
    ],
    signals: [
      {
        id: 'sig-01',
        title: 'High Capital Asset ($188M)',
        severity: 'LOW',
        category: 'valuation',
        description: 'Newbuild parity of $260M and 4-year yard backlog provide strong floor.',
        timestamp: '13 Sep 2026 15:00 UTC',
      },
    ],
  },
  {
    id: 114,
    name: 'AL GHARIYA',
    imoNumber: 'IMO 9397114',
    vesselClass: 'LNG Carrier',
    vesselType: 'Liquefied Gas Carrier',
    marketSegment: 'Gas Carrier',
    dwt: 122000,
    grossTonnage: 136000,
    lightweightTons: 39040,
    yearBuilt: 2008,
    ageYears: 18.7,
    flag: 'Marshall Islands (MHL)',
    registeredOwner: 'Qatar Gas Transport Co (Nakilat)',
    commercialOperator: 'Qatargas Operating Co',
    status: 'In Transit',
    currentPort: 'Ras Laffan Loading',
    currentMarketValueUsdM: 118.0,
    previousMarketValueUsdM: 116.5,
    change1mUsdM: +1.5,
    change1mPct: +1.3,
    change3mUsdM: +3.2,
    change3mPct: +2.8,
    change1yUsdM: +6.0,
    change1yPct: +5.4,
    valuationPerDwtUsd: 967.2,
    newbuildingParityUsdM: 260.0,
    demolitionScrapValueUsdM: 20.5,
    scrapRatePerLdtUsd: 525,
    valuationPremiumOverScrapUsdM: 97.5,
    scrapFloorPct: 17.4,
    valuationConfidence: 'Medium',
    lastAppraisalDate: '13 Sep 2026',
    valuationModel: 'BKI Signal Automated Freight & S&P Matrix v4.2',
    marketPosition: 'Below Market',
    segmentPercentile: 72,
    marketTrend: 'Stable',
    comparableAverageValueUsdM: 135.0,
    comparablePremiumPct: -12.6,
    historicalPoints: buildHistorySeries(118.0, 20.5, 122000, 182.0, 185.0),
    drivers: [
      {
        id: 'drv-01',
        name: 'Steam Turbine Efficiency Discount',
        impactPct: -22.0,
        direction: 'negative',
        category: 'specifications',
        explanation: 'Higher boil-off rate and fuel burn result in CII Band E rating and value discount.',
      },
    ],
    signals: [
      {
        id: 'sig-01',
        title: 'CII Regulatory Discount Risk',
        severity: 'HIGH',
        category: 'depreciation',
        description: 'Asset value subject to discount as European terminals prioritize low-emission LNG carriers.',
        timestamp: '12 Sep 2026 13:00 UTC',
      },
    ],
  },
  {
    id: 115,
    name: 'EVER FORWARD',
    imoNumber: 'IMO 9850551',
    vesselClass: 'Container Neo-Panamax',
    vesselType: 'Fully Cellular Container',
    marketSegment: 'Container',
    dwt: 132000,
    grossTonnage: 118000,
    lightweightTons: 36960, // 28% of DWT
    yearBuilt: 2020,
    ageYears: 6.7,
    flag: 'Hong Kong (HKG)',
    registeredOwner: 'Evergreen Marine Corp',
    commercialOperator: 'Ocean Alliance',
    status: 'In Transit',
    currentPort: 'Singapore Strait Westbound',
    currentMarketValueUsdM: 128.0,
    previousMarketValueUsdM: 125.0,
    change1mUsdM: +3.0,
    change1mPct: +2.4,
    change3mUsdM: +7.5,
    change3mPct: +6.2,
    change1yUsdM: +16.0,
    change1yPct: +14.3,
    valuationPerDwtUsd: 969.7,
    newbuildingParityUsdM: 155.0,
    demolitionScrapValueUsdM: 19.4,
    scrapRatePerLdtUsd: 525,
    valuationPremiumOverScrapUsdM: 108.6,
    scrapFloorPct: 15.2,
    valuationConfidence: 'High',
    lastAppraisalDate: '13 Sep 2026',
    valuationModel: 'BKI Signal Automated Freight & S&P Matrix v4.2',
    marketPosition: 'Above Market',
    segmentPercentile: 18,
    marketTrend: 'Rising',
    comparableAverageValueUsdM: 112.5,
    comparablePremiumPct: +13.8,
    historicalPoints: buildHistorySeries(128.0, 19.4, 132000, 112.5, 115.0),
    drivers: [
      {
        id: 'drv-01',
        name: 'Neo-Panamax Route Versatility',
        impactPct: +16.5,
        direction: 'positive',
        category: 'freight',
        explanation: '12,000 TEU capacity can transit expanded Panama Canal and transpacific corridors.',
      },
    ],
    signals: [
      {
        id: 'sig-01',
        title: 'Container Asset Value Outperformance',
        severity: 'LOW',
        category: 'valuation',
        description: 'Vessel valuation jumped +14.3% YoY driven by Red Sea diversion demand.',
        timestamp: '13 Sep 2026 11:30 UTC',
      },
    ],
  },
  {
    id: 116,
    name: 'MSC TIANSHAN',
    imoNumber: 'IMO 9744647',
    vesselClass: 'Container Neo-Panamax',
    vesselType: 'Fully Cellular Container',
    marketSegment: 'Container',
    dwt: 145000,
    grossTonnage: 140000,
    lightweightTons: 40600,
    yearBuilt: 2016,
    ageYears: 10.7,
    flag: 'Liberia (LBR)',
    registeredOwner: 'Mediterranean Shipping Company (MSC)',
    commercialOperator: 'MSC Mediterranean',
    status: 'In Transit',
    currentPort: 'Suez Southbound',
    currentMarketValueUsdM: 98.5,
    previousMarketValueUsdM: 96.2,
    change1mUsdM: +2.3,
    change1mPct: +2.4,
    change3mUsdM: +5.1,
    change3mPct: +5.5,
    change1yUsdM: +11.2,
    change1yPct: +12.8,
    valuationPerDwtUsd: 679.3,
    newbuildingParityUsdM: 165.0,
    demolitionScrapValueUsdM: 21.3,
    scrapRatePerLdtUsd: 525,
    valuationPremiumOverScrapUsdM: 77.2,
    scrapFloorPct: 21.6,
    valuationConfidence: 'High',
    lastAppraisalDate: '13 Sep 2026',
    valuationModel: 'BKI Signal Automated Freight & S&P Matrix v4.2',
    marketPosition: 'At Market',
    segmentPercentile: 36,
    marketTrend: 'Rising',
    comparableAverageValueUsdM: 95.0,
    comparablePremiumPct: +3.7,
    historicalPoints: buildHistorySeries(98.5, 21.3, 145000, 112.5, 115.0),
    drivers: [
      {
        id: 'drv-01',
        name: 'Strong Boxship Charter Rate Backlog',
        impactPct: +11.0,
        direction: 'positive',
        category: 'freight',
        explanation: 'Multi-year time charter fixture rates locking in substantial forward cash flows.',
      },
    ],
    signals: [
      {
        id: 'sig-01',
        title: 'Solid Neo-Panamax Secondary Liquidity',
        severity: 'LOW',
        category: 'market',
        description: 'Vessel valuation stable with low scrap sensitivity.',
        timestamp: '12 Sep 2026 15:15 UTC',
      },
    ],
  },
  {
    id: 117,
    name: 'CAPE PROVIDENCE',
    imoNumber: 'IMO 9432110',
    vesselClass: 'Capesize',
    vesselType: 'Dry Bulk Carrier',
    marketSegment: 'Dry Bulk',
    dwt: 175000,
    grossTonnage: 91000,
    lightweightTons: 29750,
    yearBuilt: 2010,
    ageYears: 16.7,
    flag: 'Marshall Islands (MHL)',
    registeredOwner: 'Providence Maritime Corp',
    commercialOperator: 'Oldendorff Carriers',
    status: 'At Anchorage',
    currentPort: 'Port Hedland Anchorage',
    currentMarketValueUsdM: 24.5,
    previousMarketValueUsdM: 24.0,
    change1mUsdM: +0.5,
    change1mPct: +2.1,
    change3mUsdM: +0.9,
    change3mPct: +3.8,
    change1yUsdM: +1.6,
    change1yPct: +7.0,
    valuationPerDwtUsd: 140.0,
    newbuildingParityUsdM: 74.5,
    demolitionScrapValueUsdM: 15.6,
    scrapRatePerLdtUsd: 525,
    valuationPremiumOverScrapUsdM: 8.9,
    scrapFloorPct: 63.7,
    valuationConfidence: 'High',
    lastAppraisalDate: '13 Sep 2026',
    valuationModel: 'BKI Signal Automated Freight & S&P Matrix v4.2',
    marketPosition: 'Below Market',
    segmentPercentile: 78, // Bottom 22%
    marketTrend: 'Stable',
    comparableAverageValueUsdM: 27.0,
    comparablePremiumPct: -9.3,
    historicalPoints: buildHistorySeries(24.5, 15.6, 175000, 54.8, 56.0),
    drivers: [
      {
        id: 'drv-01',
        name: 'Near-Demolition Scrap Dominance',
        impactPct: +24.0,
        direction: 'positive',
        category: 'demolition',
        explanation: 'Scrap value of $15.6M represents 63.7% of total market value.',
      },
      {
        id: 'drv-02',
        name: 'Severe Age Depreciation (16.7 yrs)',
        impactPct: -28.0,
        direction: 'negative',
        category: 'age',
        explanation: 'Approaching fourth special survey; major tier 1 miners restrict commercial chartering.',
      },
    ],
    signals: [
      {
        id: 'sig-01',
        title: 'Scrap Floor Candidate Alert',
        severity: 'HIGH',
        category: 'demolition',
        description: 'Market premium over scrap is only $8.9M. Demolition becomes economically attractive if steel prices spike.',
        timestamp: '13 Sep 2026 07:30 UTC',
      },
    ],
  },
  {
    id: 118,
    name: 'ISLAND TRANSIT',
    imoNumber: 'IMO 9600123',
    vesselClass: 'Aframax',
    vesselType: 'Crude Oil Tanker',
    marketSegment: 'Crude / Clean Tanker',
    dwt: 109000,
    grossTonnage: 59800,
    lightweightTons: 17985,
    yearBuilt: 2014,
    ageYears: 12.7,
    flag: 'Liberia (LBR)',
    registeredOwner: 'Island Maritime Carriers',
    commercialOperator: 'Teekay Tankers Ltd',
    status: 'In Transit',
    currentPort: 'Singapore Anchorage',
    currentMarketValueUsdM: 42.0,
    previousMarketValueUsdM: 41.2,
    change1mUsdM: +0.8,
    change1mPct: +1.9,
    change3mUsdM: +1.8,
    change3mPct: +4.5,
    change1yUsdM: +4.2,
    change1yPct: +11.1,
    valuationPerDwtUsd: 385.3,
    newbuildingParityUsdM: 72.0,
    demolitionScrapValueUsdM: 9.4,
    scrapRatePerLdtUsd: 525,
    valuationPremiumOverScrapUsdM: 32.6,
    scrapFloorPct: 22.4,
    valuationConfidence: 'High',
    lastAppraisalDate: '13 Sep 2026',
    valuationModel: 'BKI Signal Automated Freight & S&P Matrix v4.2',
    marketPosition: 'At Market',
    segmentPercentile: 45,
    marketTrend: 'Rising',
    comparableAverageValueUsdM: 41.5,
    comparablePremiumPct: +1.2,
    historicalPoints: buildHistorySeries(42.0, 9.4, 109000, 56.4, 57.0),
    drivers: [
      {
        id: 'drv-01',
        name: 'Sanctioned Trade Ton-Mile Displacement',
        impactPct: +8.5,
        direction: 'positive',
        category: 'sp_market',
        explanation: 'Mainstream compliant Aframax fleet benefiting from dislocation in Russian and Iranian trade lanes.',
      },
    ],
    signals: [
      {
        id: 'sig-01',
        title: 'Healthy S&P Demand for 10-15yr Aframax',
        severity: 'LOW',
        category: 'market',
        description: 'Consistent buyer interest from private European and Middle Eastern operators.',
        timestamp: '11 Sep 2026 16:00 UTC',
      },
    ],
  },
];
