/**
 * SIH 26006 Maritime Intelligence Platform
 * Module 10: Fixture Recap & Share Modal
 */

import React, { useState, useMemo } from 'react';
import { Copy, Check, Download } from 'lucide-react';
import { Modal } from '../../../components/ui/Modal';
import type { FixtureRecord } from '../../../types/fixture';

interface FixtureShareModalProps {
  isOpen: boolean;
  onClose: () => void;
  fixture: FixtureRecord | null;
}

export const FixtureShareModal: React.FC<FixtureShareModalProps> = ({
  isOpen,
  onClose,
  fixture,
}) => {
  const [copied, setCopied] = useState(false);

  const recapText = useMemo(() => {
    if (!fixture) return '';

    const lines = [
      '=====================================================',
      `COMMERCIAL FIXTURE RECAP: ${fixture.fixture_reference}`,
      '=====================================================',
      `Status: ${fixture.status.toUpperCase().replace('_', ' ')}`,
      `Fixture Date: ${new Date(fixture.fixture_date).toLocaleDateString()}`,
      `Charter Party Form: ${fixture.charter_party_form}`,
      '',
      '1. VESSEL PARTICULAR:',
      `   Name: ${fixture.vessel_name}`,
      `   IMO: ${fixture.vessel_imo}`,
      `   Type: ${fixture.vessel_type}`,
      `   DWT: ${fixture.vessel_dwt.toLocaleString()} MT`,
      '',
      '2. CONTRACTING PARTIES:',
      `   Charterer: ${fixture.charterer}`,
      `   Broker: ${fixture.charterer_broker || 'Direct'}`,
      `   Disponent Owner: ${fixture.owner_entity || 'Maritime Fleet Holdings Ltd'}`,
      '',
      '3. CARGO & CONSIGNMENT:',
      `   Commodity: ${fixture.commodity}`,
      `   Category: ${fixture.cargo_type}`,
      `   Quantity: ${fixture.quantity_tons.toLocaleString()} MT`,
      '',
      '4. MULTI-PORT ROTATION:',
      ...fixture.ports.map(
        (p) =>
          `   #${p.sequence} ${p.port_name} (${p.country}) [${p.port_type.toUpperCase()}]` +
          (p.eta ? ` - ETA: ${p.eta}` : '') +
          (p.etd ? ` - ETD: ${p.etd}` : '')
      ),
      '',
      '5. COMMERCIAL FREIGHT & RATES:',
      `   Agreed Rate: ${fixture.rate_formatted}`,
      `   Rate Basis: ${fixture.rate_type.replace('_', ' ').toUpperCase()} (${fixture.rate_currency})`,
      fixture.demurrage_usd_day ? `   Demurrage: $${fixture.demurrage_usd_day.toLocaleString()} / day` : null,
      fixture.commission_percent ? `   Commission: ${fixture.commission_percent}% Total` : null,
      `   Laycan Window: ${fixture.laycan_start} to ${fixture.laycan_end}`,
      '',
      fixture.rate_notes ? `6. SPECIAL CLAUSES & TERMS:\n   ${fixture.rate_notes}\n` : null,
      fixture.notes ? `7. DESK NOTES:\n   ${fixture.notes}\n` : null,
      '=====================================================',
      'Generated by SIH 26006 Maritime Cargo Intelligence Platform',
      '=====================================================',
    ];

    return lines.filter(Boolean).join('\n');
  }, [fixture]);

  if (!fixture) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(recapText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownloadJSON = () => {
    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(fixture, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `${fixture.fixture_reference}_recap.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={`Fixture Recap: ${fixture.fixture_reference}`}
      maxWidth="620px"
    >
      <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
        <p style={{ margin: 0, fontSize: '0.8125rem', color: 'var(--color-text-secondary)' }}>
          Standard commercial fixture confirmation format for broker desks, charterers, and operations teams:
        </p>

        {/* Formatted Text Box */}
        <div
          style={{
            position: 'relative',
            backgroundColor: 'var(--color-bg-subtle, #0f172a)',
            color: '#f8fafc',
            fontFamily: 'monospace',
            fontSize: '0.75rem',
            lineHeight: 1.4,
            padding: '1rem',
            borderRadius: '8px',
            maxHeight: '340px',
            overflowY: 'auto',
            whiteSpace: 'pre-wrap',
            border: '1px solid var(--color-border)',
          }}
        >
          {recapText}
        </div>

        {/* Modal Actions */}
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingTop: '0.75rem',
            borderTop: '1px solid var(--color-border)',
          }}
        >
          <button
            type="button"
            className="btn btn-secondary btn-sm"
            onClick={handleDownloadJSON}
            style={{ display: 'inline-flex', alignItems: 'center', gap: '5px' }}
          >
            <Download size={14} /> Download JSON
          </button>

          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <button type="button" className="btn btn-secondary btn-sm" onClick={onClose}>
              Close
            </button>
            <button
              type="button"
              className="btn btn-primary btn-sm"
              onClick={handleCopy}
              style={{ display: 'inline-flex', alignItems: 'center', gap: '5px' }}
            >
              {copied ? <Check size={14} /> : <Copy size={14} />}
              {copied ? 'Copied to Clipboard!' : 'Copy Recap'}
            </button>
          </div>
        </div>
      </div>
    </Modal>
  );
};
